In [2]:
import glob
import json
from classify_leaves_goals_org_phys_tech import classify_leaf_goal, leaf_goals_of

### Build the goal model from iso27001.json, AIRMF.json, iso42001.json, NIST.json, and CIS.json

In [2]:
%run build_goal_models_ISO27001.py # goal_models_ISO27001/
%run build_goal_models_ISO42001.py # goal_models_ISO42001/
%run build_goal_models_NIST.py     # goal_models_NIST/
%run build_goal_models_CIS.py      # goal_models_CIS/
%run build_goal_models_AIRMF.py    # goal_models_AIRMF/

========================================================================
G0  Provide management direction for information security  (A.5.1)
  G1  Provide management direction and support for information security in accordance with business requirements and relevant laws and regulations
    G1.1  [A.5.1.1] A set of policies for information security shall be defined,...
      G1.1.1     Define a set of policies for information security
      G1.1.2     Approve a set of policies for information security   [agent: management]
      G1.1.3     Publish a set of policies for information security
      G1.1.4     Communicate a set of policies for information security to employees and relevant external parties
    G1.2  [A.5.1.2] The policies for information security shall be reviewed at p...
      G1.2.1     Review the policies for information security at planned intervals to ensure their continuing suitability, adequacy and effectiveness
      G1.2.2     Review the policies for information security if significant changes occur to ensure their continuing suitability, adequacy and effectiveness

========================================================================
G0  Establish internal organization  (A.6.1)
  G1  Establish a management framework to initiate and control the implementation and operation of information security within the organization
    G1.1  [A.6.1.1] All information security responsibilities shall be defined a...
      G1.1.1     Define all information security responsibilities
      G1.1.2     Allocate all information security responsibilities
    G1.2  [A.6.1.2] Conflicting duties and areas of responsibility shall be segr...
      G1.2.1     Segregate conflicting duties and areas of responsibility to reduce opportunities for unauthorized or unintentional modification or misuse of the organization's assets
    G1.3  [A.6.1.3] Appropriate contacts with relevant authorities shall be main...
      G1.3.1     Maintain appropriate contacts with relevant authorities
    G1.4  [A.6.1.4] Appropriate contacts with special interest groups or other s...
      G1.4.1     Maintain appropriate contacts with special interest groups or other specialist security forums and professional associations
    G1.5  [A.6.1.5] Information security shall be addressed in project managemen...
      G1.5.1     Address information security in project management, regardless of the type of the project

========================================================================
G0  Secure mobile devices and teleworking  (A.6.2)
  G1  Ensure the security of teleworking and use of mobile devices
    G1.1  [A.6.2.1] A policy and supporting security measures shall be adopted t...
      G1.1.1     Adopt a policy and supporting security measures to manage the risks introduced by using mobile devices
    G1.2  [A.6.2.2] A policy and supporting security measures shall be implement...
      G1.2.1     Implement a policy and supporting security measures to protect information accessed
      G1.2.2     Process a policy and supporting security measures
      G1.2.3     Store a policy and supporting security measures at teleworking sites

========================================================================
G0  Ensure personnel security before employment  (A.7.1)
  G1  Ensure that employees and contractors understand their responsibilities and are suitable for the roles for which they are considered
    G1.1  [A.7.1.1] Background verification checks on all candidates for employm...
      G1.1.1     Carry out background verification checks on all candidates for employment in accordance with relevant laws, regulations and ethics
    G1.2  [A.7.1.2] The contractual agreements with employees and contractors sh...
      G1.2.1     State their and the organization's responsibilities for information security   [agent: The contractual agreements with employees and contractors]

========================================================================
G0  Manage information security responsibilities  (A.7.2)
  G1  Ensure that employees and contractors are aware of and fulfil their information security responsibilities
    G1.1  [A.7.2.1] Management shall require all employees and contractors to ap...
      G1.1.1     Require all employees and contractors to apply information security in accordance with the established policies and procedures of the organization   [agent: Management]
    G1.2  [A.7.2.2] All employees of the organization and, where relevant, contr...
      G1.2.1     Receive appropriate awareness education and training and regular updates in organizational policies and procedures, as relevant for their job function   [agent: All employees of the organization and, where relevant, contractors]
    G1.3  [A.7.2.3] There shall be a formal and communicated disciplinary proces...
      G1.3.1     Establish a formal and communicated disciplinary process in place to take action against employees who have committed an information security breach

========================================================================
G0  Manage termination and change of employment  (A.7.3)
  G1  Protect the organization's interests as part of the process of changing or terminating employment
    G1.1  [A.7.3.1] Information security responsibilities and duties that remain...
      G1.1.1     Define information security responsibilities and duties that remain valid after termination or change of employment
      G1.1.2     Communicate information security responsibilities and duties that remain valid after termination or change of employment to the employee or contractor
      G1.1.3     Enforce information security responsibilities and duties that remain valid after termination or change of employment

========================================================================
G0  Assign responsibility for assets  (A.8.1)
  G1  Identify organizational assets and define appropriate protection responsibilities
    G1.1  [A.8.1.1] Assets associated with information and information processin...
      G1.1.1     Identify assets associated with information and information processing facilities and an inventory of these assets shall be drawn up
      G1.1.2     Maintain assets associated with information and information processing facilities
    G1.2  [A.8.1.2] Assets maintained in the inventory shall be owned....
      G1.2.1     Ensure assets maintained in the inventory are owned
    G1.3  [A.8.1.3] Rules for the acceptable use of information and of assets as...
      G1.3.1     Identify rules for the acceptable use of information and of assets associated with information and information processing facilities
      G1.3.2     Document rules for the acceptable use of information and of assets associated with information and information processing facilities
      G1.3.3     Implement rules for the acceptable use of information and of assets associated with information and information processing facilities
    G1.4  [A.8.1.4] All employees and external party users shall return all of t...
      G1.4.1     Return all of the organizational assets in their possession upon termination of their employment, contract or agreement   [agent: All employees and external party users]

========================================================================
G0  Ensure information classification  (A.8.2)
  G1  Ensure that information receives an appropriate level of protection in accordance with its importance to the organization
    G1.1  [A.8.2.1] Information shall be classified in terms of legal requiremen...
      G1.1.1     Classify information in terms of legal requirements, value, criticality and sensitivity to unauthorised disclosure or modification
    G1.2  [A.8.2.2] An appropriate set of procedures for information labelling s...
      G1.2.1     Develop an appropriate set of procedures for information labelling
      G1.2.2     Implement an appropriate set of procedures for information labelling in accordance with the information classification scheme adopted by the organization
    G1.3  [A.8.2.3] Procedures for handling assets shall be developed and implem...
      G1.3.1     Develop procedures for handling assets
      G1.3.2     Implement procedures for handling assets in accordance with the information classification scheme adopted by the organization

========================================================================
G0  Control media handling  (A.8.3)
  G1  Prevent unauthorized disclosure, modification, removal or destruction of information stored on media
    G1.1  [A.8.3.1] Procedures shall be implemented for the management of remova...
      G1.1.1     Implement procedures for the management of removable media in accordance with the classification scheme adopted by the organization
    G1.2  [A.8.3.2] Media shall be disposed of securely when no longer required,...
      G1.2.1     Dispose of media securely when no longer required, using formal procedures
    G1.3  [A.8.3.3] Media containing information shall be protected against unau...
      G1.3.1     Protect media containing information against unauthorized access, misuse or corruption during transportation

========================================================================
G0  Establish business requirements of access control  (A.9.1)
  G1  Limit access to information and information processing facilities
    G1.1  [A.9.1.1] An access control policy shall be established, documented an...
      G1.1.1     Establish an access control policy
      G1.1.2     Document an access control policy
      G1.1.3     Review an access control policy based on business and information security requirements
    G1.2  [A.9.1.2] Users shall only be provided with access to the network and ...
      G1.2.1     Only be provided with access to the network and network services that they have been specifically authorized to use   [agent: Users]

========================================================================
G0  Ensure user access management  (A.9.2)
  G1  Ensure authorized user access and prevent unauthorized access to systems and services
    G1.1  [A.9.2.1] A formal user registration and de-registration process shall...
      G1.1.1     Implement a formal user registration and de-registration process to enable assignment of access rights
    G1.2  [A.9.2.2] A formal user access provisioning process shall be implement...
      G1.2.1     Implement a formal user access provisioning process to assign or revoke access rights for all user types to all systems and services
    G1.3  [A.9.2.3] The allocation and use of privileged access rights shall be ...
      G1.3.1     Restrict the allocation and use of privileged access rights
      G1.3.2     Control the allocation and use of privileged access rights
    G1.4  [A.9.2.4] The allocation of secret authentication information shall be...
      G1.4.1     Control the allocation of secret authentication information through a formal management process
    G1.5  [A.9.2.5] Asset owners shall review users' access rights at regular in...
      G1.5.1     Review users' access rights at regular intervals   [agent: Asset owners]
    G1.6  [A.9.2.6] The access rights of all employees and external party users ...
      G1.6.1     Remove the access rights of all employees and external party users to information and information processing facilities upon termination of their employment, contract or agreement
      G1.6.2     Adjust the access rights of all employees and external party users to information and information processing facilities upon change

========================================================================
G0  Define user responsibilities  (A.9.3)
  G1  Make users accountable for safeguarding their authentication information
    G1.1  [A.9.3.1] Users shall be required to follow the organization's practic...
      G1.1.1     Require users to follow the organization's practices in the use of secret authentication information

========================================================================
G0  Ensure system and application access control  (A.9.4)
  G1  Prevent unauthorized access to systems and applications
    G1.1  [A.9.4.1] Access to information and application system functions shall...
      G1.1.1     Restrict access to information and application system functions in accordance with the access control policy
    G1.2  [A.9.4.2] Where required by the access control policy, access to syste...
      G1.2.1     Control where required by the access control policy, access to systems and applications   [agent: a secure log-on procedure]
    G1.3  [A.9.4.3] Password management systems shall be interactive and shall e...
      G1.3.1     Ensure password management systems are interactive and shall ensure quality passwords
    G1.4  [A.9.4.4] The use of utility programs that might be capable of overrid...
      G1.4.1     Restrict the use of utility programs that might be capable of overriding system and application controls and tightly controlled
    G1.5  [A.9.4.5] Access to program source code shall be restricted....
      G1.5.1     Restrict access to program source code

========================================================================
G0  Apply cryptographic controls  (A.10.1)
  G1  Ensure proper and effective use of cryptography to protect the confidentiality, authenticity and/or integrity of information
    G1.1  [A.10.1.1] A policy on the use of cryptographic controls for protection...
      G1.1.1     Develop a policy on the use of cryptographic controls for protection of information
      G1.1.2     Implement a policy on the use of cryptographic controls for protection of information
    G1.2  [A.10.1.2] A policy on the use, protection and lifetime of cryptographi...
      G1.2.1     Develop a policy on the use, protection and lifetime of cryptographic keys
      G1.2.2     Implement a policy on the use, protection and lifetime of cryptographic keys through their whole lifecycle

========================================================================
G0  Protect secure areas  (A.11.1)
  G1  Prevent unauthorized physical access, damage and interference to the organization's information and information processing facilities
    G1.1  [A.11.1.1] Security perimeters shall be defined and used to protect are...
      G1.1.1     Define security perimeters
      G1.1.2     Use security perimeters to protect areas that contain either sensitive or critical information and information processing facilities
    G1.2  [A.11.1.2] Secure areas shall be protected by appropriate entry control...
      G1.2.1     Protect secure areas to ensure that only authorized personnel are allowed access   [agent: appropriate entry controls]
    G1.3  [A.11.1.3] Physical security for offices, rooms and facilities shall be...
      G1.3.1     Design physical security for offices, rooms and facilities
      G1.3.2     Apply physical security for offices, rooms and facilities
    G1.4  [A.11.1.4] Physical protection against natural disasters, malicious att...
      G1.4.1     Design physical protection against natural disasters, malicious attack or accidents
      G1.4.2     Apply physical protection against natural disasters, malicious attack or accidents
    G1.5  [A.11.1.5] Procedures for working in secure areas shall be designed and...
      G1.5.1     Design procedures for working in secure areas
      G1.5.2     Apply procedures for working in secure areas
    G1.6  [A.11.1.6] Access points such as delivery and loading areas and other p...
      G1.6.1     Control access points such as delivery and loading areas and other points where unauthorized persons could enter the premises and, if possible
      G1.6.2     Isolate access points such as delivery and loading areas and other points where unauthorized persons could enter the premises from information processing facilities to avoid unauthorized access

15 clauses --> one JSON each in goal_models_ISO27001/

========================================================================
G0  Ensure AI policy  (A.2)
  G1  Establish an AI policy
    G1.1  [A.2.2] The organization shall establish an AI policy....
      G1.1.1     Establish an AI policy   [agent: The organization]
    G1.2  [A.2.3] The AI policy shall be aligned with other relevant organizat...
      G1.2.1     Align the AI policy with other relevant organizational policies
    G1.3  [A.2.4] The AI policy shall be reviewed at planned intervals and whe...
      G1.3.1     Review the AI policy at planned intervals and when significant changes occur

========================================================================
G0  Ensure roles and responsibilities for AI  (A.3)
  G1  Define roles and responsibilities for AI and Assign roles and responsibilities for AI
    G1.1  [A.3.2] Roles and responsibilities for AI shall be defined and assig...
      G1.1.1     Define roles and responsibilities for AI
      G1.1.2     Assign roles and responsibilities for AI
    G1.2  [A.3.3] AI issues shall be reported, escalated, and addressed....
      G1.2.1     Report AI issues
      G1.2.2     Escalate AI issues
      G1.2.3     Address AI issues
    G1.3  [A.3.4] Responsibilities toward affected interested parties shall be...
      G1.3.1     Define responsibilities toward affected interested parties

========================================================================
G0  Ensure resources  (A.4)
  G1  Determine appropriate resources for AI systems and Provide appropriate resources for AI systems
    G1.1  [A.4.2] Appropriate resources for AI systems shall be determined and...
      G1.1.1     Determine appropriate resources for AI systems
      G1.1.2     Provide appropriate resources for AI systems
    G1.2  [A.4.3] Competence required for AI-related roles shall be establishe...
      G1.2.1     Establish competence required for AI-related roles
      G1.2.2     Maintain competence required for AI-related roles
    G1.3  [A.4.4] Personnel shall be aware of AI policy, risks, and responsibi...
      G1.3.1     Ensure personnel are aware of AI policy, risks, and responsibilities

========================================================================
G0  Ensure AI system impact assessment  (A.5)
  G1  Perform impact assessments for AI systems
    G1.1  [A.5.2] Impact assessments shall be performed for AI systems....
      G1.1.1     Perform impact assessments for AI systems
    G1.2  [A.5.3] Impact assessments shall be performed at appropriate times a...
      G1.2.1     Perform impact assessments at appropriate times across the AI lifecycle
    G1.3  [A.5.4] Impact assessment results shall be reviewed and updated when...
      G1.3.1     Review impact assessment results
      G1.3.2     Update impact assessment results when needed
    G1.4  [A.5.5] Records of impact assessments shall be retained....
      G1.4.1     Retain records of impact assessments

========================================================================
G0  Ensure AI system design and development  (A.6)
  G1  Design AI systems and Develop AI systems according to defined requirements
    G1.1  [A.6.2] AI systems shall be designed and developed according to defi...
      G1.1.1     Design AI systems
      G1.1.2     Develop AI systems according to defined requirements
    G1.2  [A.6.3] AI systems shall be verified and validated before use....
      G1.2.1     Verify AI systems
      G1.2.2     Validate AI systems before use
    G1.3  [A.6.4] Deployment of AI systems shall be controlled....
      G1.3.1     Control deployment of AI systems
    G1.4  [A.6.5] AI systems shall be operated and monitored....
      G1.4.1     Operate AI systems
      G1.4.2     Monitor AI systems
    G1.5  [A.6.6] AI systems shall be maintained over their lifecycle....
      G1.5.1     Maintain AI systems over their lifecycle

========================================================================

### Leaf goals classification into TECH, PHYS, and ORG

In [7]:
files = glob.glob("goal_models_NIST/*.json") # <-- change the path

# Exclude files ending with these suffixes
exclude_suffixes = ("_leaf_goals_classified.json", ".operationalized_embeddings.json", ".operationalized_qwen.json")
files = [p for p in files if not p.endswith(exclude_suffixes)]

for path in files:
    with open(path, encoding="utf-8") as f:
        model = json.load(f)

    # classify the leaf goals in the goal model
    classify_leaf_goal(model)

    # print leaf goals
    leaves = leaf_goals_of(model)
    for leaf in leaves:
        print(f"{leaf['goal_id']} [{leaf['class']}] {leaf['goal_name']}")

    n_org = sum(1 for lf in leaves if lf["class"] == "ORG")
    print(f"\n{len(leaves)} leaf goals: {n_org} ORG, {len(leaves) - n_org} TECH")

    out = path.rsplit(".json", 1)[0] + "_leaf_goals_classified.json"
    with open(out, "w", encoding="utf-8") as f:
        json.dump(model, f, indent=2, ensure_ascii=False)
    print(f"--> {out}")

G1.1.1 [ORG] Develop policy and procedures to facilitate the implementation of access control controls
G1.1.2 [PHYS] Document policy and procedures to facilitate the implementation of access control controls
G1.1.3 [ORG] Disseminate policy and procedures to facilitate the implementation of access control controls
G1.2.1 [TECH] Manage information system accounts, including establishing, activating, modifying, disabling, and removing accounts
G1.3.1 [TECH] Enforce approved authorizations for logical access to information and system resources
G1.4.1 [TECH] Enforce approved authorizations for controlling information flow within the system and between interconnected systems
G1.5.1 [TECH] Separate duties and responsibilities to reduce opportunities for unauthorized activity
G1.6.1 [TECH] Employ the principle of least privilege, allowing only authorized accesses needed to accomplish assigned tasks
G1.7.1 [TECH] Enforce a limit on consecutive invalid logon attempts by a user during a time period
G1.8.1 [TECH] Display an approved system use notification message before granting access
G1.9.1 [TECH] Prevent further access to the system by initiating a device lock after defined conditions
G1.10.1 [TECH] Terminate a user session after a condition of inactivity or upon user logout

12 leaf goals: 2 ORG, 10 TECH
--> goal_models_NIST\AC_leaf_goals_classified.json
G1.1.1 [ORG] Develop policy and procedures to facilitate implementation of audit and accountability controls
G1.1.2 [ORG] Document policy and procedures to facilitate implementation of audit and accountability controls
G1.1.3 [ORG] Disseminate policy and procedures to facilitate implementation of audit and accountability controls
G1.2.1 [TECH] Determine that the information system can log events relevant to security monitoring, investigations, and incident response
G1.3.1 [ORG] Generate audit records containing information sufficient to support monitoring, analysis, investigation, and reporting
G1.4.1 [ORG] Allocate audit record storage capacity to store audit records for the defined retention period
G1.5.1 [ORG] Respond to audit logging process failures by taking appropriate action

7 leaf goals: 6 ORG, 1 TECH
--> goal_models_NIST\AU_leaf_goals_classified.json
G1.1.1 [ORG] Develop policy and procedures to facilitate implementation of assessment, authorization, and monitoring controls
G1.1.2 [ORG] Document policy and procedures to facilitate implementation of assessment, authorization, and monitoring controls
G1.1.3 [ORG] Disseminate policy and procedures to facilitate implementation of assessment, authorization, and monitoring controls
G1.2.1 [TECH] Assess the controls in the system and environment of operation to determine if they are implemented correctly and operating as intended
G1.3.1 [TECH] Authorize connections and information exchange between systems using interconnection agreements
G1.4.1 [ORG] Develop a plan of action and milestones for the system
G1.4.2 [ORG] Implement a plan of action and milestones for the system

7 leaf goals: 5 ORG, 2 TECH
--> goal_models_NIST\CA_leaf_goals_classified.json
G1.1.1 [ORG] Develop policy and procedures to facilitate implementation of configuration management controls
G1.1.2 [ORG] Document policy and procedures to facilitate implementation of configuration management controls
G1.1.3 [ORG] Disseminate policy and procedures to facilitate implementation of configuration management controls
G1.2.1 [TECH] Develop a current baseline configuration of the system
G1.2.2 [TECH] Document a current baseline configuration of the system
G1.2.3 [TECH] Maintain a current baseline configuration of the system
G1.3.1 [TECH] Document changes to the system
G1.3.2 [ORG] Approve changes to the system
G1.3.3 [TECH] Monitor changes to the system
G1.4.1 [TECH] Analyze changes to the system to determine potential security impact prior to change implementation

10 leaf goals: 4 ORG, 6 TECH
--> goal_models_NIST\CM_leaf_goals_classified.json
G1.1.1 [ORG] Develop policy and procedures to facilitate implementation of contingency planning controls
G1.1.2 [ORG] Document policy and procedures to facilitate implementation of contingency planning controls
G1.1.3 [ORG] Disseminate policy and procedures to facilitate implementation of contingency planning controls
G1.2.1 [ORG] Develop a contingency plan for the system
G1.2.2 [ORG] Document a contingency plan for the system
G1.2.3 [TECH] Maintain a contingency plan for the system
G1.3.1 [ORG] Provide contingency training to system users and personnel
G1.4.1 [TECH] Test contingency plans for the system
G1.5.1 [TECH] Conduct backups of user-level and system-level information

9 leaf goals: 6 ORG, 3 TECH
--> goal_models_NIST\CP_leaf_goals_classified.json
G1.1.1 [PHYS] Develop policy and procedures to facilitate implementation of identification and authentication controls
G1.1.2 [PHYS] Document policy and procedures to facilitate implementation of identification and authentication controls
G1.1.3 [ORG] Disseminate policy and procedures to facilitate implementation of identification and authentication controls
G1.2.1 [TECH] Uniquely identify organizational users, processes acting on behalf of users, and devices
G1.2.2 [TECH] Uniquely authenticate organizational users, processes acting on behalf of users, and devices
G1.3.1 [TECH] Uniquely identify devices before establishing a connection
G1.3.2 [PHYS] Uniquely authenticate devices before establishing a connection
G1.4.1 [TECH] Manage user identifiers by, for example, disabling inactive identifiers and ensuring uniqueness
G1.5.1 [TECH] Manage information system authenticators by defining initial content, changing them periodically, and protecting them

9 leaf goals: 1 ORG, 8 TECH
--> goal_models_NIST\IA_leaf_goals_classified.json
G1.1.1 [ORG] Develop policy and procedures to facilitate incident response controls
G1.1.2 [ORG] Document policy and procedures to facilitate incident response controls
G1.1.3 [ORG] Disseminate policy and procedures to facilitate incident response controls
G1.2.1 [ORG] Provide incident response training to personnel with incident response roles and responsibilities
G1.3.1 [ORG] Test the incident response capability
G1.4.1 [ORG] Implement an incident handling capability for security incidents

6 leaf goals: 6 ORG, 0 TECH
--> goal_models_NIST\IR_leaf_goals_classified.json
G1.1.1 [ORG] Develop policy and procedures to facilitate maintenance controls
G1.1.2 [ORG] Document policy and procedures to facilitate maintenance controls
G1.1.3 [ORG] Disseminate policy and procedures to facilitate maintenance controls
G1.2.1 [TECH] Perform maintenance on system components in a controlled manner
G1.3.1 [TECH] Approve maintenance tools
G1.3.2 [TECH] Control maintenance tools
G1.3.3 [TECH] Monitor maintenance tools

7 leaf goals: 3 ORG, 4 TECH
--> goal_models_NIST\MA_leaf_goals_classified.json
G1.1.1 [PHYS] Develop policy and procedures to facilitate media protection controls
G1.1.2 [PHYS] Document policy and procedures to facilitate media protection controls
G1.1.3 [PHYS] Disseminate policy and procedures to facilitate media protection controls
G1.2.1 [PHYS] Restrict access to digital and non-digital media containing information
G1.3.1 [TECH] Protect information system media until the media are destroyed or sanitized using approved equipment, techniques, and procedures

5 leaf goals: 0 ORG, 5 TECH
--> goal_models_NIST\MP_leaf_goals_classified.json
G1.1.1 [ORG] Develop policy and procedures to facilitate physical and environmental protection controls
G1.1.2 [ORG] Document policy and procedures to facilitate physical and environmental protection controls
G1.1.3 [ORG] Disseminate policy and procedures to facilitate physical and environmental protection controls
G1.2.1 [PHYS] Develop physical access authorizations for designated areas
G1.2.2 [PHYS] Maintain physical access authorizations for designated areas
G1.3.1 [PHYS] Enforce physical access control to the facility and areas within the facility
G1.4.1 [PHYS] Monitor physical access to the facility and physical areas containing systems

7 leaf goals: 3 ORG, 4 TECH
--> goal_models_NIST\PE_leaf_goals_classified.json
G1.1.1 [ORG] Develop policy and procedures to facilitate planning controls
G1.1.2 [ORG] Document policy and procedures to facilitate planning controls
G1.1.3 [ORG] Disseminate policy and procedures to facilitate planning controls
G1.2.1 [TECH] Develop system security and privacy plans that describe the system boundary, security requirements, and controls

4 leaf goals: 3 ORG, 1 TECH
--> goal_models_NIST\PL_leaf_goals_classified.json
G1.1.1 [ORG] Develop an organization-wide information security program plan
G1.1.2 [ORG] Document an organization-wide information security program plan
G1.1.3 [ORG] Disseminate an organization-wide information security program plan
G1.2.1 [PHYS] Plan for and allocate security and privacy resources

4 leaf goals: 3 ORG, 1 TECH
--> goal_models_NIST\PM_leaf_goals_classified.json
G1.1.1 [ORG] Develop policy and procedures to facilitate personnel security controls
G1.1.2 [PHYS] Document policy and procedures to facilitate personnel security controls
G1.1.3 [ORG] Disseminate policy and procedures to facilitate personnel security controls
G1.2.1 [ORG] Assign a risk designation to organizational positions
G1.3.1 [PHYS] Screen individuals prior to authorizing access to the information system

5 leaf goals: 3 ORG, 2 TECH
--> goal_models_NIST\PS_leaf_goals_classified.json
G1.1.1 [ORG] Develop policy and procedures to facilitate privacy controls
G1.1.2 [ORG] Document policy and procedures to facilitate privacy controls
G1.1.3 [ORG] Disseminate policy and procedures to facilitate privacy controls
G1.2.1 [ORG] Determine the legal authority and other requirements to process personally identifiable information

4 leaf goals: 4 ORG, 0 TECH
--> goal_models_NIST\PT_leaf_goals_classified.json
G1.1.1 [ORG] Develop policy and procedures to facilitate risk assessment controls
G1.1.2 [ORG] Document policy and procedures to facilitate risk assessment controls
G1.1.3 [ORG] Disseminate policy and procedures to facilitate risk assessment controls
G1.2.1 [TECH] Categorize the system and information processed, stored, and transmitted by the system
G1.3.1 [ORG] Conduct a risk assessment to determine the risk to organizational operations, assets, individuals, other organizations, and the Nation

5 leaf goals: 4 ORG, 1 TECH
--> goal_models_NIST\RA_leaf_goals_classified.json
G1.1.1 [ORG] Develop policy and procedures to facilitate system and services acquisition controls
G1.1.2 [ORG] Document policy and procedures to facilitate system and services acquisition controls
G1.1.3 [ORG] Disseminate policy and procedures to facilitate system and services acquisition controls
G1.2.1 [TECH] Determine resources required to protect the system
G1.2.2 [TECH] Document resources required to protect the system
G1.2.3 [TECH] Allocate resources required to protect the system
G1.3.1 [ORG] Manage the system using a system development life cycle
G1.4.1 [ORG] Include security and privacy requirements in acquisition contracts and related documents

8 leaf goals: 5 ORG, 3 TECH
--> goal_models_NIST\SA_leaf_goals_classified.json
G1.1.1 [TECH] Develop policy and procedures to facilitate system and communications protection controls
G1.1.2 [PHYS] Document policy and procedures to facilitate system and communications protection controls
G1.1.3 [PHYS] Disseminate policy and procedures to facilitate system and communications protection controls
G1.2.1 [TECH] Monitor communications at external boundaries and key internal boundaries
G1.2.2 [PHYS] Control communications at external boundaries and key internal boundaries
G1.3.1 [TECH] Protect the confidentiality and integrity of transmitted information
G1.4.1 [TECH] Establish cryptographic keys for the system
G1.4.2 [TECH] Manage cryptographic keys for the system

8 leaf goals: 0 ORG, 8 TECH
--> goal_models_NIST\SC_leaf_goals_classified.json
G1.1.1 [ORG] Develop policy and procedures to facilitate system and information integrity controls
G1.1.2 [ORG] Document policy and procedures to facilitate system and information integrity controls
G1.1.3 [ORG] Disseminate policy and procedures to facilitate system and information integrity controls
G1.2.1 [TECH] Identify system flaws in a timely manner
G1.2.2 [ORG] Report system flaws in a timely manner
G1.2.3 [TECH] Correct system flaws in a timely manner
G1.3.1 [TECH] Implement malicious code protection mechanisms at system entry and exit points to detect and eradicate malicious code
G1.4.1 [TECH] Monitor the system to detect attacks and indicators of potential attacks

8 leaf goals: 4 ORG, 4 TECH
--> goal_models_NIST\SI_leaf_goals_classified.json
G1.1.1 [ORG] Develop policy and procedures to facilitate supply chain risk management controls
G1.1.2 [ORG] Document policy and procedures to facilitate supply chain risk management controls
G1.1.3 [ORG] Disseminate policy and procedures to facilitate supply chain risk management controls
G1.2.1 [ORG] Develop a supply chain risk management plan for the system, system component, or service
G1.3.1 [ORG] Establish controls and processes for managing supply chain risks
G1.3.2 [ORG] Document controls and processes for managing supply chain risks
G1.3.3 [ORG] Implement controls and processes for managing supply chain risks

7 leaf goals: 7 ORG, 0 TECH
--> goal_models_NIST\SR_leaf_goals_classified.json

### Operationalization (using embedding technique)

In [4]:
%run operationalization_via_embeddings.py

Loading D3FEND...
Loading OntoSecAI...

Knowledge-base index
------------------------------------------------------------
D3FEND defensive techniques : 271
OntoSecAI mitigations        : 81

Loading embedding model: sentence-transformers/all-mpnet-base-v2

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1521.70it/s]

Encoding D3FEND techniques...

Batches: 100%|██████████| 5/5 [00:06<00:00,  1.34s/it]

Encoding OntoSecAI mitigations...

Batches: 100%|██████████| 2/2 [00:02<00:00,  1.17s/it]

==========================================================================================
ISO 27001 — 15 goal-model files
==========================================================================================

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.10.1_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 25.42it/s]

  Develop a policy on the use of cryptographic controls for protection of  | D3FEND=0.483 ✓ | OntoSecAI=0.553 ✓
  Implement a policy on the use of cryptographic controls for protection o | D3FEND=0.482 ✓ | OntoSecAI=0.563 ✓
  Develop a policy on the use, protection and lifetime of cryptographic ke | D3FEND=0.377 · | OntoSecAI=0.435 ·
  Implement a policy on the use, protection and lifetime of cryptographic  | D3FEND=0.387 · | OntoSecAI=0.443 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.10.1_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.11.1_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]

  Define security perimeters                                               | D3FEND=0.519 ✓ | OntoSecAI=0.369 ·
  Use security perimeters to protect areas that contain either sensitive o | D3FEND=0.552 ✓ | OntoSecAI=0.471 ✓
  Protect secure areas to ensure that only authorized personnel are allowe | D3FEND=0.636 ✓ | OntoSecAI=0.500 ✓
  Design physical security for offices, rooms and facilities               | D3FEND=0.503 ✓ | OntoSecAI=0.432 ·
  Apply physical security for offices, rooms and facilities                | D3FEND=0.555 ✓ | OntoSecAI=0.432 ·
  Design physical protection against natural disasters, malicious attack o | D3FEND=0.418 · | OntoSecAI=0.470 ✓
  Apply physical protection against natural disasters, malicious attack or | D3FEND=0.463 ✓ | OntoSecAI=0.415 ·
  Design procedures for working in secure areas                            | D3FEND=0.473 ✓ | OntoSecAI=0.484 ✓
  Apply procedures for working in secure areas                             | D3FEND=0.477 ✓ | OntoSecAI=0.449 ·
  Control access points such as delivery and loading areas and other point | D3FEND=0.630 ✓ | OntoSecAI=0.490 ✓
  Isolate access points such as delivery and loading areas and other point | D3FEND=0.597 ✓ | OntoSecAI=0.537 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.11.1_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.5.1_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]

  Define a set of policies for information security                        | D3FEND=0.560 ✓ | OntoSecAI=0.528 ✓
  Approve a set of policies for information security                       | D3FEND=0.490 ✓ | OntoSecAI=0.526 ✓
  Publish a set of policies for information security                       | D3FEND=0.484 ✓ | OntoSecAI=0.477 ✓
  Communicate a set of policies for information security to employees and  | D3FEND=0.426 · | OntoSecAI=0.408 ·
  Review the policies for information security at planned intervals to ens | D3FEND=0.424 · | OntoSecAI=0.443 ·
  Review the policies for information security if significant changes occu | D3FEND=0.394 · | OntoSecAI=0.401 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.5.1_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.6.1_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 14.80it/s]

  Define all information security responsibilities                         | D3FEND=0.412 · | OntoSecAI=0.469 ✓
  Allocate all information security responsibilities                       | D3FEND=0.447 · | OntoSecAI=0.521 ✓
  Segregate conflicting duties and areas of responsibility to reduce oppor | D3FEND=0.450 · | OntoSecAI=0.381 ·
  Maintain appropriate contacts with relevant authorities                  | D3FEND=0.284 · | OntoSecAI=0.247 ·
  Maintain appropriate contacts with special interest groups or other spec | D3FEND=0.330 · | OntoSecAI=0.418 ·
  Address information security in project management, regardless of the ty | D3FEND=0.380 · | OntoSecAI=0.405 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.6.1_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.6.2_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 28.63it/s]

  Adopt a policy and supporting security measures to manage the risks intr | D3FEND=0.431 · | OntoSecAI=0.441 ·
  Implement a policy and supporting security measures to protect informati | D3FEND=0.589 ✓ | OntoSecAI=0.601 ✓
  Process a policy and supporting security measures                        | D3FEND=0.564 ✓ | OntoSecAI=0.532 ✓
  Store a policy and supporting security measures at teleworking sites     | D3FEND=0.449 · | OntoSecAI=0.416 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.6.2_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.7.1_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 44.05it/s]

  Carry out background verification checks on all candidates for employmen | D3FEND=0.306 · | OntoSecAI=0.353 ·
  State their and the organization's responsibilities for information secu | D3FEND=0.403 · | OntoSecAI=0.401 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.7.1_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.7.2_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 31.99it/s]

  Require all employees and contractors to apply information security in a | D3FEND=0.421 · | OntoSecAI=0.406 ·
  Receive appropriate awareness education and training and regular updates | D3FEND=0.301 · | OntoSecAI=0.254 ·
  Establish a formal and communicated disciplinary process in place to tak | D3FEND=0.404 · | OntoSecAI=0.338 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.7.2_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.7.3_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 31.48it/s]

  Define information security responsibilities and duties that remain vali | D3FEND=0.356 · | OntoSecAI=0.361 ·
  Communicate information security responsibilities and duties that remain | D3FEND=0.329 · | OntoSecAI=0.341 ·
  Enforce information security responsibilities and duties that remain val | D3FEND=0.344 · | OntoSecAI=0.367 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.7.3_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.8.1_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 17.81it/s]

  Identify assets associated with information and information processing f | D3FEND=0.526 ✓ | OntoSecAI=0.427 ·
  Maintain assets associated with information and information processing f | D3FEND=0.439 · | OntoSecAI=0.423 ·
  Ensure assets maintained in the inventory are owned                      | D3FEND=0.504 ✓ | OntoSecAI=0.544 ✓
  Identify rules for the acceptable use of information and of assets assoc | D3FEND=0.408 · | OntoSecAI=0.406 ·
  Document rules for the acceptable use of information and of assets assoc | D3FEND=0.398 · | OntoSecAI=0.367 ·
  Implement rules for the acceptable use of information and of assets asso | D3FEND=0.388 · | OntoSecAI=0.411 ·
  Return all of the organizational assets in their possession upon termina | D3FEND=0.299 · | OntoSecAI=0.166 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.8.1_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.8.2_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 21.75it/s]

  Classify information in terms of legal requirements, value, criticality  | D3FEND=0.438 · | OntoSecAI=0.515 ✓
  Develop an appropriate set of procedures for information labelling       | D3FEND=0.334 · | OntoSecAI=0.310 ·
  Implement an appropriate set of procedures for information labelling in  | D3FEND=0.376 · | OntoSecAI=0.365 ·
  Develop procedures for handling assets                                   | D3FEND=0.464 ✓ | OntoSecAI=0.372 ·
  Implement procedures for handling assets in accordance with the informat | D3FEND=0.498 ✓ | OntoSecAI=0.425 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.8.2_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.8.3_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 32.93it/s]

  Implement procedures for the management of removable media in accordance | D3FEND=0.467 ✓ | OntoSecAI=0.325 ·
  Dispose of media securely when no longer required, using formal procedur | D3FEND=0.499 ✓ | OntoSecAI=0.289 ·
  Protect media containing information against unauthorized access, misuse | D3FEND=0.571 ✓ | OntoSecAI=0.523 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.8.3_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.9.1_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 28.94it/s]

  Establish an access control policy                                       | D3FEND=0.618 ✓ | OntoSecAI=0.626 ✓
  Document an access control policy                                        | D3FEND=0.615 ✓ | OntoSecAI=0.564 ✓
  Review an access control policy based on business and information securi | D3FEND=0.539 ✓ | OntoSecAI=0.514 ✓
  Only be provided with access to the network and network services that th | D3FEND=0.540 ✓ | OntoSecAI=0.489 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.9.1_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.9.2_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 13.19it/s]

  Implement a formal user registration and de-registration process to enab | D3FEND=0.605 ✓ | OntoSecAI=0.509 ✓
  Implement a formal user access provisioning process to assign or revoke  | D3FEND=0.584 ✓ | OntoSecAI=0.531 ✓
  Restrict the allocation and use of privileged access rights              | D3FEND=0.530 ✓ | OntoSecAI=0.625 ✓
  Control the allocation and use of privileged access rights               | D3FEND=0.545 ✓ | OntoSecAI=0.633 ✓
  Control the allocation of secret authentication information through a fo | D3FEND=0.529 ✓ | OntoSecAI=0.540 ✓
  Review users' access rights at regular intervals                         | D3FEND=0.422 · | OntoSecAI=0.415 ·
  Remove the access rights of all employees and external party users to in | D3FEND=0.486 ✓ | OntoSecAI=0.450 ·
  Adjust the access rights of all employees and external party users to in | D3FEND=0.457 ✓ | OntoSecAI=0.424 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.9.2_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.9.3_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.64it/s]

  Require users to follow the organization's practices in the use of secre | D3FEND=0.406 · | OntoSecAI=0.492 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.9.3_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.9.4_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 22.11it/s]

  Restrict access to information and application system functions in accor | D3FEND=0.577 ✓ | OntoSecAI=0.634 ✓
  Control where required by the access control policy, access to systems a | D3FEND=0.566 ✓ | OntoSecAI=0.642 ✓
  Ensure password management systems are interactive and shall ensure qual | D3FEND=0.517 ✓ | OntoSecAI=0.413 ·
  Restrict the use of utility programs that might be capable of overriding | D3FEND=0.581 ✓ | OntoSecAI=0.518 ✓
  Restrict access to program source code                                   | D3FEND=0.509 ✓ | OntoSecAI=0.453 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.9.4_leaf_goals_classified.operationalized_embeddings.json

==========================================================================================
ISO 42001 — 9 goal-model files
==========================================================================================

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.10_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 38.09it/s]

  Define requirements for suppliers and external providers                 | D3FEND=0.258 · | OntoSecAI=0.411 ·
  Identify requirements from customers and users                           | D3FEND=0.260 · | OntoSecAI=0.301 ·
  Address requirements from customers and users                            | D3FEND=0.244 · | OntoSecAI=0.263 ·
  Monitor Third-party relationships                                        | D3FEND=0.429 · | OntoSecAI=0.397 ·
  Review Third-party relationships                                         | D3FEND=0.316 · | OntoSecAI=0.317 ·
  Establish appropriate contractual controls                               | D3FEND=0.312 · | OntoSecAI=0.333 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.10_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.2_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 41.96it/s]

  Establish an AI policy                                                   | D3FEND=0.385 · | OntoSecAI=0.514 ✓
  Align the AI policy with other relevant organizational policies          | D3FEND=0.356 · | OntoSecAI=0.487 ✓
  Review the AI policy at planned intervals and when significant changes o | D3FEND=0.321 · | OntoSecAI=0.471 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.2_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.3_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 39.47it/s]

  Define roles and responsibilities for AI                                 | D3FEND=0.335 · | OntoSecAI=0.436 ·
  Assign roles and responsibilities for AI                                 | D3FEND=0.329 · | OntoSecAI=0.452 ✓
  Report AI issues                                                         | D3FEND=0.303 · | OntoSecAI=0.466 ✓
  Escalate AI issues                                                       | D3FEND=0.302 · | OntoSecAI=0.478 ✓
  Address AI issues                                                        | D3FEND=0.316 · | OntoSecAI=0.504 ✓
  Define responsibilities toward affected interested parties               | D3FEND=0.321 · | OntoSecAI=0.294 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.3_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.4_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 29.47it/s]

  Determine appropriate resources for AI systems                           | D3FEND=0.224 · | OntoSecAI=0.388 ·
  Provide appropriate resources for AI systems                             | D3FEND=0.228 · | OntoSecAI=0.435 ·
  Establish competence required for AI-related roles                       | D3FEND=0.288 · | OntoSecAI=0.470 ✓
  Maintain competence required for AI-related roles                        | D3FEND=0.247 · | OntoSecAI=0.435 ·
  Ensure personnel are aware of AI policy, risks, and responsibilities     | D3FEND=0.381 · | OntoSecAI=0.569 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.4_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.5_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 30.56it/s]

  Perform impact assessments for AI systems                                | D3FEND=0.389 · | OntoSecAI=0.499 ✓
  Perform impact assessments at appropriate times across the AI lifecycle  | D3FEND=0.345 · | OntoSecAI=0.440 ·
  Review impact assessment results                                         | D3FEND=0.196 · | OntoSecAI=0.272 ·
  Update impact assessment results when needed                             | D3FEND=0.230 · | OntoSecAI=0.214 ·
  Retain records of impact assessments                                     | D3FEND=0.298 · | OntoSecAI=0.250 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.5_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.6_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 30.70it/s]

  Design AI systems                                                        | D3FEND=0.237 · | OntoSecAI=0.423 ·
  Develop AI systems according to defined requirements                     | D3FEND=0.236 · | OntoSecAI=0.417 ·
  Verify AI systems                                                        | D3FEND=0.326 · | OntoSecAI=0.585 ✓
  Validate AI systems before use                                           | D3FEND=0.352 · | OntoSecAI=0.593 ✓
  Control deployment of AI systems                                         | D3FEND=0.298 · | OntoSecAI=0.566 ✓
  Operate AI systems                                                       | D3FEND=0.252 · | OntoSecAI=0.441 ·
  Monitor AI systems                                                       | D3FEND=0.424 · | OntoSecAI=0.536 ✓
  Maintain AI systems over their lifecycle                                 | D3FEND=0.267 · | OntoSecAI=0.517 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.6_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.7_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 29.46it/s]

  Acquire data used for AI systems appropriately                           | D3FEND=0.304 · | OntoSecAI=0.558 ✓
  Define data quality requirements                                         | D3FEND=0.333 · | OntoSecAI=0.386 ·
  Check data quality requirements                                          | D3FEND=0.342 · | OntoSecAI=0.440 ·
  Control data preparation activities                                      | D3FEND=0.424 · | OntoSecAI=0.388 ·
  Track data provenance                                                    | D3FEND=0.485 ✓ | OntoSecAI=0.418 ·
  Maintain data provenance                                                 | D3FEND=0.465 ✓ | OntoSecAI=0.414 ·
  Define data selection criteria                                           | D3FEND=0.314 · | OntoSecAI=0.262 ·
  Apply data selection criteria                                            | D3FEND=0.246 · | OntoSecAI=0.254 ·
  Handle data securely and appropriately                                   | D3FEND=0.427 · | OntoSecAI=0.515 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.7_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.8_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 44.29it/s]

  Provide relevant information about AI systems to interested parties      | D3FEND=0.236 · | OntoSecAI=0.596 ✓
  Support transparency of AI system behavior                               | D3FEND=0.345 · | OntoSecAI=0.521 ✓
  Make appropriate explainability information available                    | D3FEND=0.216 · | OntoSecAI=0.387 ·
  Receive guidance for the intended use of AI systems                      | D3FEND=0.293 · | OntoSecAI=0.461 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.8_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.9_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 32.27it/s]

  Use AI systems responsibly                                               | D3FEND=0.319 · | OntoSecAI=0.549 ✓
  Define human oversight                                                   | D3FEND=0.304 · | OntoSecAI=0.339 ·
  Implement human oversight                                                | D3FEND=0.456 ✓ | OntoSecAI=0.523 ✓
  Monitor use of AI systems for unintended behavior                        | D3FEND=0.458 ✓ | OntoSecAI=0.552 ✓
  Monitor inputs and outputs of AI systems as needed                       | D3FEND=0.377 · | OntoSecAI=0.452 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.9_leaf_goals_classified.operationalized_embeddings.json

==========================================================================================
NIST — 19 goal-model files
==========================================================================================

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\AC_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]

  Develop policy and procedures to facilitate the implementation of access | D3FEND=0.597 ✓ | OntoSecAI=0.538 ✓
  Document policy and procedures to facilitate the implementation of acces | D3FEND=0.576 ✓ | OntoSecAI=0.529 ✓
  Disseminate policy and procedures to facilitate the implementation of ac | D3FEND=0.606 ✓ | OntoSecAI=0.532 ✓
  Manage information system accounts, including establishing, activating,  | D3FEND=0.479 ✓ | OntoSecAI=0.338 ·
  Enforce approved authorizations for logical access to information and sy | D3FEND=0.612 ✓ | OntoSecAI=0.651 ✓
  Enforce approved authorizations for controlling information flow within  | D3FEND=0.589 ✓ | OntoSecAI=0.696 ✓
  Separate duties and responsibilities to reduce opportunities for unautho | D3FEND=0.505 ✓ | OntoSecAI=0.507 ✓
  Employ the principle of least privilege, allowing only authorized access | D3FEND=0.594 ✓ | OntoSecAI=0.646 ✓
  Enforce a limit on consecutive invalid logon attempts by a user during a | D3FEND=0.389 · | OntoSecAI=0.396 ·
  Display an approved system use notification message before granting acce | D3FEND=0.388 · | OntoSecAI=0.499 ✓
  Prevent further access to the system by initiating a device lock after d | D3FEND=0.610 ✓ | OntoSecAI=0.461 ✓
  Terminate a user session after a condition of inactivity or upon user lo | D3FEND=0.399 · | OntoSecAI=0.252 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\AC_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\AU_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 19.36it/s]

  Develop policy and procedures to facilitate implementation of audit and  | D3FEND=0.321 · | OntoSecAI=0.336 ·
  Document policy and procedures to facilitate implementation of audit and | D3FEND=0.337 · | OntoSecAI=0.314 ·
  Disseminate policy and procedures to facilitate implementation of audit  | D3FEND=0.369 · | OntoSecAI=0.320 ·
  Determine that the information system can log events relevant to securit | D3FEND=0.498 ✓ | OntoSecAI=0.551 ✓
  Generate audit records containing information sufficient to support moni | D3FEND=0.396 · | OntoSecAI=0.353 ·
  Allocate audit record storage capacity to store audit records for the de | D3FEND=0.251 · | OntoSecAI=0.301 ·
  Respond to audit logging process failures by taking appropriate action   | D3FEND=0.379 · | OntoSecAI=0.372 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\AU_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\CA_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 16.80it/s]

  Develop policy and procedures to facilitate implementation of assessment | D3FEND=0.428 · | OntoSecAI=0.396 ·
  Document policy and procedures to facilitate implementation of assessmen | D3FEND=0.440 · | OntoSecAI=0.403 ·
  Disseminate policy and procedures to facilitate implementation of assess | D3FEND=0.418 · | OntoSecAI=0.388 ·
  Assess the controls in the system and environment of operation to determ | D3FEND=0.479 ✓ | OntoSecAI=0.391 ·
  Authorize connections and information exchange between systems using int | D3FEND=0.483 ✓ | OntoSecAI=0.568 ✓
  Develop a plan of action and milestones for the system                   | D3FEND=0.328 · | OntoSecAI=0.287 ·
  Implement a plan of action and milestones for the system                 | D3FEND=0.311 · | OntoSecAI=0.289 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\CA_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\CM_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 17.01it/s]

  Develop policy and procedures to facilitate implementation of configurat | D3FEND=0.502 ✓ | OntoSecAI=0.359 ·
  Document policy and procedures to facilitate implementation of configura | D3FEND=0.531 ✓ | OntoSecAI=0.344 ·
  Disseminate policy and procedures to facilitate implementation of config | D3FEND=0.486 ✓ | OntoSecAI=0.331 ·
  Develop a current baseline configuration of the system                   | D3FEND=0.360 · | OntoSecAI=0.224 ·
  Document a current baseline configuration of the system                  | D3FEND=0.422 · | OntoSecAI=0.251 ·
  Maintain a current baseline configuration of the system                  | D3FEND=0.354 · | OntoSecAI=0.286 ·
  Document changes to the system                                           | D3FEND=0.387 · | OntoSecAI=0.254 ·
  Approve changes to the system                                            | D3FEND=0.231 · | OntoSecAI=0.344 ·
  Monitor changes to the system                                            | D3FEND=0.564 ✓ | OntoSecAI=0.408 ·
  Analyze changes to the system to determine potential security impact pri | D3FEND=0.554 ✓ | OntoSecAI=0.478 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\CM_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\CP_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 17.58it/s]

  Develop policy and procedures to facilitate implementation of contingenc | D3FEND=0.413 · | OntoSecAI=0.395 ·
  Document policy and procedures to facilitate implementation of contingen | D3FEND=0.448 · | OntoSecAI=0.396 ·
  Disseminate policy and procedures to facilitate implementation of contin | D3FEND=0.413 · | OntoSecAI=0.409 ·
  Develop a contingency plan for the system                                | D3FEND=0.444 · | OntoSecAI=0.424 ·
  Document a contingency plan for the system                               | D3FEND=0.426 · | OntoSecAI=0.406 ·
  Maintain a contingency plan for the system                               | D3FEND=0.429 · | OntoSecAI=0.450 ·
  Provide contingency training to system users and personnel               | D3FEND=0.415 · | OntoSecAI=0.415 ·
  Test contingency plans for the system                                    | D3FEND=0.419 · | OntoSecAI=0.374 ·
  Conduct backups of user-level and system-level information               | D3FEND=0.369 · | OntoSecAI=0.484 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\CP_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\IA_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 14.13it/s]

  Develop policy and procedures to facilitate implementation of identifica | D3FEND=0.507 ✓ | OntoSecAI=0.507 ✓
  Document policy and procedures to facilitate implementation of identific | D3FEND=0.539 ✓ | OntoSecAI=0.522 ✓
  Disseminate policy and procedures to facilitate implementation of identi | D3FEND=0.500 ✓ | OntoSecAI=0.502 ✓
  Uniquely identify organizational users, processes acting on behalf of us | D3FEND=0.606 ✓ | OntoSecAI=0.463 ✓
  Uniquely authenticate organizational users, processes acting on behalf o | D3FEND=0.573 ✓ | OntoSecAI=0.582 ✓
  Uniquely identify devices before establishing a connection               | D3FEND=0.451 ✓ | OntoSecAI=0.376 ·
  Uniquely authenticate devices before establishing a connection           | D3FEND=0.484 ✓ | OntoSecAI=0.439 ·
  Manage user identifiers by, for example, disabling inactive identifiers  | D3FEND=0.451 ✓ | OntoSecAI=0.406 ·
  Manage information system authenticators by defining initial content, ch | D3FEND=0.573 ✓ | OntoSecAI=0.616 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\IA_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\IR_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 28.05it/s]

  Develop policy and procedures to facilitate incident response controls   | D3FEND=0.383 · | OntoSecAI=0.375 ·
  Document policy and procedures to facilitate incident response controls  | D3FEND=0.400 · | OntoSecAI=0.349 ·
  Disseminate policy and procedures to facilitate incident response contro | D3FEND=0.409 · | OntoSecAI=0.372 ·
  Provide incident response training to personnel with incident response r | D3FEND=0.328 · | OntoSecAI=0.318 ·
  Test the incident response capability                                    | D3FEND=0.428 · | OntoSecAI=0.343 ·
  Implement an incident handling capability for security incidents         | D3FEND=0.417 · | OntoSecAI=0.477 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\IR_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\MA_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 27.01it/s]

  Develop policy and procedures to facilitate maintenance controls         | D3FEND=0.400 · | OntoSecAI=0.362 ·
  Document policy and procedures to facilitate maintenance controls        | D3FEND=0.436 · | OntoSecAI=0.361 ·
  Disseminate policy and procedures to facilitate maintenance controls     | D3FEND=0.404 · | OntoSecAI=0.383 ·
  Perform maintenance on system components in a controlled manner          | D3FEND=0.434 · | OntoSecAI=0.360 ·
  Approve maintenance tools                                                | D3FEND=0.356 · | OntoSecAI=0.324 ·
  Control maintenance tools                                                | D3FEND=0.482 ✓ | OntoSecAI=0.341 ·
  Monitor maintenance tools                                                | D3FEND=0.464 ✓ | OntoSecAI=0.313 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\MA_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\MP_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 22.60it/s]

  Develop policy and procedures to facilitate media protection controls    | D3FEND=0.513 ✓ | OntoSecAI=0.374 ·
  Document policy and procedures to facilitate media protection controls   | D3FEND=0.518 ✓ | OntoSecAI=0.443 ·
  Disseminate policy and procedures to facilitate media protection control | D3FEND=0.490 ✓ | OntoSecAI=0.406 ·
  Restrict access to digital and non-digital media containing information  | D3FEND=0.552 ✓ | OntoSecAI=0.440 ·
  Protect information system media until the media are destroyed or saniti | D3FEND=0.522 ✓ | OntoSecAI=0.521 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\MP_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\PE_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 24.43it/s]

  Develop policy and procedures to facilitate physical and environmental p | D3FEND=0.371 · | OntoSecAI=0.290 ·
  Document policy and procedures to facilitate physical and environmental  | D3FEND=0.390 · | OntoSecAI=0.277 ·
  Disseminate policy and procedures to facilitate physical and environment | D3FEND=0.391 · | OntoSecAI=0.290 ·
  Develop physical access authorizations for designated areas              | D3FEND=0.602 ✓ | OntoSecAI=0.507 ✓
  Maintain physical access authorizations for designated areas             | D3FEND=0.594 ✓ | OntoSecAI=0.501 ✓
  Enforce physical access control to the facility and areas within the fac | D3FEND=0.688 ✓ | OntoSecAI=0.507 ✓
  Monitor physical access to the facility and physical areas containing sy | D3FEND=0.613 ✓ | OntoSecAI=0.488 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\PE_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\PL_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 28.53it/s]

  Develop policy and procedures to facilitate planning controls            | D3FEND=0.361 · | OntoSecAI=0.294 ·
  Document policy and procedures to facilitate planning controls           | D3FEND=0.334 · | OntoSecAI=0.241 ·
  Disseminate policy and procedures to facilitate planning controls        | D3FEND=0.373 · | OntoSecAI=0.268 ·
  Develop system security and privacy plans that describe the system bound | D3FEND=0.536 ✓ | OntoSecAI=0.533 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\PL_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\PM_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 36.76it/s]

  Develop an organization-wide information security program plan           | D3FEND=0.364 · | OntoSecAI=0.384 ·
  Document an organization-wide information security program plan          | D3FEND=0.363 · | OntoSecAI=0.378 ·
  Disseminate an organization-wide information security program plan       | D3FEND=0.321 · | OntoSecAI=0.388 ·
  Plan for and allocate security and privacy resources                     | D3FEND=0.464 ✓ | OntoSecAI=0.524 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\PM_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\PS_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 32.42it/s]

  Develop policy and procedures to facilitate personnel security controls  | D3FEND=0.503 ✓ | OntoSecAI=0.442 ·
  Document policy and procedures to facilitate personnel security controls | D3FEND=0.492 ✓ | OntoSecAI=0.435 ·
  Disseminate policy and procedures to facilitate personnel security contr | D3FEND=0.520 ✓ | OntoSecAI=0.442 ·
  Assign a risk designation to organizational positions                    | D3FEND=0.494 ✓ | OntoSecAI=0.284 ·
  Screen individuals prior to authorizing access to the information system | D3FEND=0.523 ✓ | OntoSecAI=0.569 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\PS_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\PT_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 32.16it/s]

  Develop policy and procedures to facilitate privacy controls             | D3FEND=0.461 ✓ | OntoSecAI=0.457 ✓
  Document policy and procedures to facilitate privacy controls            | D3FEND=0.444 · | OntoSecAI=0.460 ✓
  Disseminate policy and procedures to facilitate privacy controls         | D3FEND=0.456 ✓ | OntoSecAI=0.441 ·
  Determine the legal authority and other requirements to process personal | D3FEND=0.364 · | OntoSecAI=0.432 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\PT_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\RA_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 21.91it/s]

  Develop policy and procedures to facilitate risk assessment controls     | D3FEND=0.457 ✓ | OntoSecAI=0.350 ·
  Document policy and procedures to facilitate risk assessment controls    | D3FEND=0.446 · | OntoSecAI=0.328 ·
  Disseminate policy and procedures to facilitate risk assessment controls | D3FEND=0.414 · | OntoSecAI=0.334 ·
  Categorize the system and information processed, stored, and transmitted | D3FEND=0.500 ✓ | OntoSecAI=0.340 ·
  Conduct a risk assessment to determine the risk to organizational operat | D3FEND=0.527 ✓ | OntoSecAI=0.301 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\RA_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\SA_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 20.78it/s]

  Develop policy and procedures to facilitate system and services acquisit | D3FEND=0.368 · | OntoSecAI=0.332 ·
  Document policy and procedures to facilitate system and services acquisi | D3FEND=0.399 · | OntoSecAI=0.341 ·
  Disseminate policy and procedures to facilitate system and services acqu | D3FEND=0.383 · | OntoSecAI=0.352 ·
  Determine resources required to protect the system                       | D3FEND=0.585 ✓ | OntoSecAI=0.554 ✓
  Document resources required to protect the system                        | D3FEND=0.471 ✓ | OntoSecAI=0.443 ·
  Allocate resources required to protect the system                        | D3FEND=0.544 ✓ | OntoSecAI=0.678 ✓
  Manage the system using a system development life cycle                  | D3FEND=0.397 · | OntoSecAI=0.274 ·
  Include security and privacy requirements in acquisition contracts and r | D3FEND=0.351 · | OntoSecAI=0.417 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\SA_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\SC_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 22.83it/s]

  Develop policy and procedures to facilitate system and communications pr | D3FEND=0.504 ✓ | OntoSecAI=0.519 ✓
  Document policy and procedures to facilitate system and communications p | D3FEND=0.513 ✓ | OntoSecAI=0.483 ✓
  Disseminate policy and procedures to facilitate system and communication | D3FEND=0.495 ✓ | OntoSecAI=0.481 ✓
  Monitor communications at external boundaries and key internal boundarie | D3FEND=0.495 ✓ | OntoSecAI=0.414 ·
  Control communications at external boundaries and key internal boundarie | D3FEND=0.368 · | OntoSecAI=0.359 ·
  Protect the confidentiality and integrity of transmitted information     | D3FEND=0.511 ✓ | OntoSecAI=0.560 ✓
  Establish cryptographic keys for the system                              | D3FEND=0.335 · | OntoSecAI=0.421 ·
  Manage cryptographic keys for the system                                 | D3FEND=0.328 · | OntoSecAI=0.368 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\SC_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\SI_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 17.13it/s]

  Develop policy and procedures to facilitate system and information integ | D3FEND=0.422 · | OntoSecAI=0.448 ·
  Document policy and procedures to facilitate system and information inte | D3FEND=0.421 · | OntoSecAI=0.409 ·
  Disseminate policy and procedures to facilitate system and information i | D3FEND=0.415 · | OntoSecAI=0.459 ✓
  Identify system flaws in a timely manner                                 | D3FEND=0.461 ✓ | OntoSecAI=0.394 ·
  Report system flaws in a timely manner                                   | D3FEND=0.333 · | OntoSecAI=0.292 ·
  Correct system flaws in a timely manner                                  | D3FEND=0.426 · | OntoSecAI=0.414 ·
  Implement malicious code protection mechanisms at system entry and exit  | D3FEND=0.582 ✓ | OntoSecAI=0.561 ✓
  Monitor the system to detect attacks and indicators of potential attacks | D3FEND=0.590 ✓ | OntoSecAI=0.554 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\SI_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\SR_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 22.16it/s]

  Develop policy and procedures to facilitate supply chain risk management | D3FEND=0.355 · | OntoSecAI=0.435 ·
  Document policy and procedures to facilitate supply chain risk managemen | D3FEND=0.377 · | OntoSecAI=0.440 ·
  Disseminate policy and procedures to facilitate supply chain risk manage | D3FEND=0.341 · | OntoSecAI=0.435 ·
  Develop a supply chain risk management plan for the system, system compo | D3FEND=0.448 · | OntoSecAI=0.447 ·
  Establish controls and processes for managing supply chain risks         | D3FEND=0.374 · | OntoSecAI=0.454 ✓
  Document controls and processes for managing supply chain risks          | D3FEND=0.404 · | OntoSecAI=0.494 ✓
  Implement controls and processes for managing supply chain risks         | D3FEND=0.381 · | OntoSecAI=0.448 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\SR_leaf_goals_classified.operationalized_embeddings.json

==========================================================================================
CIS — 18 goal-model files
==========================================================================================

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.10_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 22.39it/s]

  Deploy Anti-Malware Software                                             | D3FEND=0.490 ✓ | OntoSecAI=0.386 ·
  Maintain Anti-Malware Software                                           | D3FEND=0.449 · | OntoSecAI=0.366 ·
  Configure Automatic Anti-Malware Signature Updates                       | D3FEND=0.425 · | OntoSecAI=0.482 ✓
  Disable Autorun and Autoplay for Removable Media                         | D3FEND=0.423 · | OntoSecAI=0.230 ·
  Configure Automatic Anti-Malware Scanning of Removable Media             | D3FEND=0.437 · | OntoSecAI=0.322 ·
  Enable Anti-Exploitation Features                                        | D3FEND=0.575 ✓ | OntoSecAI=0.576 ✓
  Centrally Manage Anti-Malware Software                                   | D3FEND=0.422 · | OntoSecAI=0.389 ·
  Use Behavior-Based Anti-Malware Software                                 | D3FEND=0.504 ✓ | OntoSecAI=0.427 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.10_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.11_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 26.94it/s]

  Establish a Data Recovery Process                                        | D3FEND=0.493 ✓ | OntoSecAI=0.329 ·
  Maintain a Data Recovery Process                                         | D3FEND=0.475 ✓ | OntoSecAI=0.371 ·
  Perform Automated Backups                                                | D3FEND=0.337 · | OntoSecAI=0.493 ✓
  Protect Recovery Data                                                    | D3FEND=0.490 ✓ | OntoSecAI=0.486 ✓
  Establish an Isolated Instance of Recovery Data                          | D3FEND=0.418 · | OntoSecAI=0.376 ·
  Maintain an Isolated Instance of Recovery Data                           | D3FEND=0.393 · | OntoSecAI=0.436 ·
  Test Data Recovery                                                       | D3FEND=0.451 ✓ | OntoSecAI=0.257 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.11_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.12_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 13.76it/s]

  Ensure Network Infrastructure is Up-to-Date                              | D3FEND=0.453 ✓ | OntoSecAI=0.340 ·
  Establish a Secure Network Architecture                                  | D3FEND=0.537 ✓ | OntoSecAI=0.532 ✓
  Maintain a Secure Network Architecture                                   | D3FEND=0.512 ✓ | OntoSecAI=0.528 ✓
  Securely Manage Network Infrastructure                                   | D3FEND=0.522 ✓ | OntoSecAI=0.458 ✓
  Establish Architecture Diagram(s)                                        | D3FEND=0.391 · | OntoSecAI=0.254 ·
  Maintain Architecture Diagram(s)                                         | D3FEND=0.324 · | OntoSecAI=0.300 ·
  Centralize Network Authentication, Authorization, and Auditing (AAA)     | D3FEND=0.480 ✓ | OntoSecAI=0.567 ✓
  Use of Secure Network Management and Communication Protocols             | D3FEND=0.487 ✓ | OntoSecAI=0.466 ✓
  Ensure Remote Devices Utilize a VPN and are Connecting to an Enterprise’ | D3FEND=0.386 · | OntoSecAI=0.347 ·
  Establish Dedicated Computing Resources for All Administrative Work      | D3FEND=0.392 · | OntoSecAI=0.401 ·
  Maintain Dedicated Computing Resources for All Administrative Work       | D3FEND=0.375 · | OntoSecAI=0.403 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.12_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.13_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

  Perform Application Layer Filtering                                      | D3FEND=0.392 · | OntoSecAI=0.398 ·
  Deploy a Host-Based Intrusion Detection Solution                         | D3FEND=0.421 · | OntoSecAI=0.432 ·
  Deploy a Network Intrusion Detection Solution                            | D3FEND=0.438 · | OntoSecAI=0.446 ·
  Perform Traffic Filtering Between Network Segments                       | D3FEND=0.501 ✓ | OntoSecAI=0.529 ✓
  Manage Access Control for Remote Assets                                  | D3FEND=0.561 ✓ | OntoSecAI=0.497 ✓
  Collect Network Traffic Flow Logs                                        | D3FEND=0.424 · | OntoSecAI=0.474 ✓
  Deploy a Host-Based Intrusion Prevention Solution                        | D3FEND=0.478 ✓ | OntoSecAI=0.509 ✓
  Deploy a Network Intrusion Prevention Solution                           | D3FEND=0.488 ✓ | OntoSecAI=0.521 ✓
  Deploy Port-Level Access Control                                         | D3FEND=0.457 ✓ | OntoSecAI=0.472 ✓
  Ensure tune Security Event Alerting Thresholds                           | D3FEND=0.474 ✓ | OntoSecAI=0.491 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.13_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.14_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 17.33it/s]

  Establish a Security Awareness Program                                   | D3FEND=0.378 · | OntoSecAI=0.421 ·
  Maintain a Security Awareness Program                                    | D3FEND=0.376 · | OntoSecAI=0.464 ✓
  Train Workforce Members to Recognize Social Engineering Attacks          | D3FEND=0.459 ✓ | OntoSecAI=0.481 ✓
  Train Workforce Members on Authentication Best Practices                 | D3FEND=0.407 · | OntoSecAI=0.467 ✓
  Train Workforce on Data Handling Best Practices                          | D3FEND=0.329 · | OntoSecAI=0.406 ·
  Train Workforce Members on Causes of Unintentional Data Exposure         | D3FEND=0.395 · | OntoSecAI=0.428 ·
  Train Workforce Members on Recognizing and Reporting Security Incidents  | D3FEND=0.398 · | OntoSecAI=0.448 ·
  Train Workforce on How to Identify and Report if Their Enterprise Assets | D3FEND=0.470 ✓ | OntoSecAI=0.481 ✓
  Train Workforce on the Dangers of Connecting to and Transmitting Enterpr | D3FEND=0.427 · | OntoSecAI=0.462 ✓
  Conduct Role-Specific Security Awareness and Skills Training             | D3FEND=0.394 · | OntoSecAI=0.537 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.14_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.15_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 18.82it/s]

  Establish an Inventory of Service Providers                              | D3FEND=0.374 · | OntoSecAI=0.340 ·
  Maintain an Inventory of Service Providers                               | D3FEND=0.400 · | OntoSecAI=0.401 ·
  Establish a Service Provider Management Policy                           | D3FEND=0.366 · | OntoSecAI=0.358 ·
  Maintain a Service Provider Management Policy                            | D3FEND=0.355 · | OntoSecAI=0.391 ·
  Classify Service Providers                                               | D3FEND=0.370 · | OntoSecAI=0.287 ·
  Ensure Service Provider Contracts Include Security Requirements          | D3FEND=0.348 · | OntoSecAI=0.485 ✓
  Assess Service Providers                                                 | D3FEND=0.273 · | OntoSecAI=0.243 ·
  Monitor Service Providers                                                | D3FEND=0.479 ✓ | OntoSecAI=0.405 ·
  Securely Decommission Service Providers                                  | D3FEND=0.439 · | OntoSecAI=0.341 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.15_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.16_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]

  Apply Secure Design Principles in Application Architectures              | D3FEND=0.491 ✓ | OntoSecAI=0.609 ✓
  Establish a Process to Accept and Address Software Vulnerabilities       | D3FEND=0.516 ✓ | OntoSecAI=0.482 ✓
  Maintain a Process to Accept and Address Software Vulnerabilities        | D3FEND=0.491 ✓ | OntoSecAI=0.475 ✓
  Perform Root Cause Analysis on Security Vulnerabilities                  | D3FEND=0.450 ✓ | OntoSecAI=0.468 ✓
  Establish an Inventory of Third-Party Software Components                | D3FEND=0.530 ✓ | OntoSecAI=0.397 ·
  Manage an Inventory of Third-Party Software Components                   | D3FEND=0.561 ✓ | OntoSecAI=0.470 ✓
  Use Up-to-Date and Trusted Third-Party Software Components               | D3FEND=0.503 ✓ | OntoSecAI=0.382 ·
  Establish a Severity Rating System and Process for Application Vulnerabi | D3FEND=0.541 ✓ | OntoSecAI=0.480 ✓
  Maintain a Severity Rating System and Process for Application Vulnerabil | D3FEND=0.517 ✓ | OntoSecAI=0.448 ·
  Use Standard Hardening Configuration Templates for Application Infrastru | D3FEND=0.557 ✓ | OntoSecAI=0.439 ·
  Separate Production and Non-Production Systems                           | D3FEND=0.304 · | OntoSecAI=0.286 ·
  Train Developers in Application Security Concepts and Secure Coding      | D3FEND=0.404 · | OntoSecAI=0.634 ✓
  Ensure leverage Vetted Modules or Services for Application Security Comp | D3FEND=0.552 ✓ | OntoSecAI=0.544 ✓
  Implement Code-Level Security Checks                                     | D3FEND=0.646 ✓ | OntoSecAI=0.614 ✓
  Conduct Application Penetration Testing                                  | D3FEND=0.398 · | OntoSecAI=0.415 ·
  Conduct Threat Modeling                                                  | D3FEND=0.506 ✓ | OntoSecAI=0.499 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.16_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.17_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 21.31it/s]

  Designate Personnel to Manage Incident Handling                          | D3FEND=0.398 · | OntoSecAI=0.330 ·
  Establish Contact Information for Reporting Security Incidents           | D3FEND=0.351 · | OntoSecAI=0.404 ·
  Maintain Contact Information for Reporting Security Incidents            | D3FEND=0.322 · | OntoSecAI=0.399 ·
  Establish an Enterprise Process for Reporting Incidents                  | D3FEND=0.374 · | OntoSecAI=0.307 ·
  Maintain an Enterprise Process for Reporting Incidents                   | D3FEND=0.404 · | OntoSecAI=0.334 ·
  Establish an Incident Response Process                                   | D3FEND=0.400 · | OntoSecAI=0.394 ·
  Maintain an Incident Response Process                                    | D3FEND=0.417 · | OntoSecAI=0.414 ·
  Assign Key Roles and Responsibilities                                    | D3FEND=0.387 · | OntoSecAI=0.367 ·
  Define Mechanisms for Communicating During Incident Response             | D3FEND=0.424 · | OntoSecAI=0.345 ·
  Conduct Routine Incident Response Exercises                              | D3FEND=0.322 · | OntoSecAI=0.267 ·
  Conduct Post-Incident Reviews                                            | D3FEND=0.333 · | OntoSecAI=0.213 ·
  Establish Security Incident Thresholds                                   | D3FEND=0.556 ✓ | OntoSecAI=0.517 ✓
  Maintain Security Incident Thresholds                                    | D3FEND=0.522 ✓ | OntoSecAI=0.513 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.17_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.18_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 42.23it/s]

  Establish a Penetration Testing Program                                  | D3FEND=0.324 · | OntoSecAI=0.370 ·
  Maintain a Penetration Testing Program                                   | D3FEND=0.334 · | OntoSecAI=0.348 ·
  Perform Periodic External Penetration Tests                              | D3FEND=0.385 · | OntoSecAI=0.301 ·
  Remediate Penetration Test Findings                                      | D3FEND=0.341 · | OntoSecAI=0.331 ·
  Validate Security Measures                                               | D3FEND=0.516 ✓ | OntoSecAI=0.567 ✓
  Perform Periodic Internal Penetration Tests                              | D3FEND=0.363 · | OntoSecAI=0.314 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.18_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.1_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 25.19it/s]

  Establish Detailed Enterprise Asset Inventory                            | D3FEND=0.543 ✓ | OntoSecAI=0.538 ✓
  Maintain Detailed Enterprise Asset Inventory                             | D3FEND=0.534 ✓ | OntoSecAI=0.571 ✓
  Address Unauthorized Assets                                              | D3FEND=0.442 · | OntoSecAI=0.339 ·
  Utilize an Active Discovery Tool                                         | D3FEND=0.343 · | OntoSecAI=0.300 ·
  Use Dynamic Host Configuration Protocol (DHCP) Logging to Update Enterpr | D3FEND=0.464 ✓ | OntoSecAI=0.428 ·
  Use a Passive Asset Discovery Tool                                       | D3FEND=0.441 · | OntoSecAI=0.253 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.1_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.2_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 34.24it/s]

  Establish a Software Inventory                                           | D3FEND=0.642 ✓ | OntoSecAI=0.494 ✓
  Maintain a Software Inventory                                            | D3FEND=0.642 ✓ | OntoSecAI=0.545 ✓
  Ensure Authorized Software is Currently Supported                        | D3FEND=0.369 · | OntoSecAI=0.373 ·
  Address Unauthorized Software                                            | D3FEND=0.414 · | OntoSecAI=0.341 ·
  Utilize Automated Software Inventory Tools                               | D3FEND=0.621 ✓ | OntoSecAI=0.530 ✓
  Allowlist Authorized Software                                            | D3FEND=0.440 · | OntoSecAI=0.452 ✓
  Allowlist Authorized Libraries                                           | D3FEND=0.358 · | OntoSecAI=0.401 ·
  Allowlist Authorized Scripts                                             | D3FEND=0.372 · | OntoSecAI=0.405 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.2_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.3_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 16.69it/s]

  Encrypt Sensitive Data in Transit                                        | D3FEND=0.394 · | OntoSecAI=0.425 ·
  Establish a Data Inventory                                               | D3FEND=0.663 ✓ | OntoSecAI=0.500 ✓
  Maintain a Data Inventory                                                | D3FEND=0.669 ✓ | OntoSecAI=0.580 ✓
  Configure Data Access Control Lists                                      | D3FEND=0.521 ✓ | OntoSecAI=0.606 ✓
  Enforce Data Retention                                                   | D3FEND=0.440 · | OntoSecAI=0.435 ·
  Securely Dispose of Data                                                 | D3FEND=0.529 ✓ | OntoSecAI=0.368 ·
  Encrypt Data on End-User Devices                                         | D3FEND=0.406 · | OntoSecAI=0.415 ·
  Establish a Data Classification Scheme                                   | D3FEND=0.329 · | OntoSecAI=0.331 ·
  Maintain a Data Classification Scheme                                    | D3FEND=0.290 · | OntoSecAI=0.379 ·
  Document Data Flows                                                      | D3FEND=0.445 · | OntoSecAI=0.279 ·
  Encrypt Data on Removable Media                                          | D3FEND=0.496 ✓ | OntoSecAI=0.325 ·
  Encrypt Sensitive Data at Rest                                           | D3FEND=0.389 · | OntoSecAI=0.450 ✓
  Segment Data Processing and Storage Based on Sensitivity                 | D3FEND=0.221 · | OntoSecAI=0.258 ·
  Deploy a Data Loss Prevention Solution                                   | D3FEND=0.490 ✓ | OntoSecAI=0.497 ✓
  Log Sensitive Data Access                                                | D3FEND=0.418 · | OntoSecAI=0.487 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.3_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.4_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 16.00it/s]

  Enforce Automatic Device Lockout on Portable End-User Devices            | D3FEND=0.572 ✓ | OntoSecAI=0.416 ·
  Establish a Secure Configuration Process for Network Infrastructure      | D3FEND=0.526 ✓ | OntoSecAI=0.489 ✓
  Maintain a Secure Configuration Process for Network Infrastructure       | D3FEND=0.488 ✓ | OntoSecAI=0.474 ✓
  Configure Automatic Session Locking on Enterprise Assets                 | D3FEND=0.435 · | OntoSecAI=0.431 ·
  Implement a Firewall on Servers                                          | D3FEND=0.514 ✓ | OntoSecAI=0.437 ·
  Manage a Firewall on Servers                                             | D3FEND=0.409 · | OntoSecAI=0.340 ·
  Implement a Firewall on End-User Devices                                 | D3FEND=0.470 ✓ | OntoSecAI=0.444 ·
  Manage a Firewall on End-User Devices                                    | D3FEND=0.440 · | OntoSecAI=0.399 ·
  Securely Manage Enterprise Assets and Software                           | D3FEND=0.445 · | OntoSecAI=0.465 ✓
  Manage Default Accounts on Enterprise Assets and Software                | D3FEND=0.355 · | OntoSecAI=0.312 ·
  Uninstall Unnecessary Services on Enterprise Assets and Software         | D3FEND=0.319 · | OntoSecAI=0.251 ·
  Disable Unnecessary Services on Enterprise Assets and Software           | D3FEND=0.356 · | OntoSecAI=0.362 ·
  Configure Trusted DNS Servers on Enterprise Assets                       | D3FEND=0.390 · | OntoSecAI=0.278 ·
  Enforce Remote Wipe Capability on Portable End-User Devices              | D3FEND=0.445 · | OntoSecAI=0.347 ·
  Separate Enterprise Workspaces on Mobile End-User Devices                | D3FEND=0.231 · | OntoSecAI=0.246 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.4_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.5_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 37.77it/s]

  Establish an Inventory of Accounts                                       | D3FEND=0.434 · | OntoSecAI=0.448 ·
  Maintain an Inventory of Accounts                                        | D3FEND=0.428 · | OntoSecAI=0.476 ✓
  Use Unique Passwords                                                     | D3FEND=0.540 ✓ | OntoSecAI=0.361 ·
  Disable Dormant Accounts                                                 | D3FEND=0.548 ✓ | OntoSecAI=0.242 ·
  Restrict Administrator Privileges to Dedicated Administrator Accounts    | D3FEND=0.420 · | OntoSecAI=0.390 ·
  Establish an Inventory of Service Accounts                               | D3FEND=0.377 · | OntoSecAI=0.439 ·
  Maintain an Inventory of Service Accounts                                | D3FEND=0.351 · | OntoSecAI=0.454 ✓
  Centralize Account Management                                            | D3FEND=0.374 · | OntoSecAI=0.290 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.5_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.6_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 24.35it/s]

  Establish an Access Granting Process                                     | D3FEND=0.541 ✓ | OntoSecAI=0.497 ✓
  Establish an Access Revoking Process                                     | D3FEND=0.554 ✓ | OntoSecAI=0.435 ·
  Require MFA for Externally-Exposed Applications                          | D3FEND=0.412 · | OntoSecAI=0.443 ·
  Require MFA for Remote Network Access                                    | D3FEND=0.448 · | OntoSecAI=0.398 ·
  Require MFA for Administrative Access                                    | D3FEND=0.480 ✓ | OntoSecAI=0.456 ✓
  Establish an Inventory of Authentication and Authorization Systems       | D3FEND=0.535 ✓ | OntoSecAI=0.587 ✓
  Maintain an Inventory of Authentication and Authorization Systems        | D3FEND=0.501 ✓ | OntoSecAI=0.631 ✓
  Centralize Access Control                                                | D3FEND=0.589 ✓ | OntoSecAI=0.559 ✓
  Define Role-Based Access Control                                         | D3FEND=0.593 ✓ | OntoSecAI=0.600 ✓
  Maintain Role-Based Access Control                                       | D3FEND=0.591 ✓ | OntoSecAI=0.629 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.6_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.7_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 23.30it/s]

  Establish a Vulnerability Management Process                             | D3FEND=0.548 ✓ | OntoSecAI=0.459 ✓
  Maintain a Vulnerability Management Process                              | D3FEND=0.494 ✓ | OntoSecAI=0.453 ✓
  Establish a Remediation Process                                          | D3FEND=0.380 · | OntoSecAI=0.217 ·
  Maintain a Remediation Process                                           | D3FEND=0.382 · | OntoSecAI=0.230 ·
  Perform Automated Operating System Patch Management                      | D3FEND=0.450 · | OntoSecAI=0.370 ·
  Perform Automated Application Patch Management                           | D3FEND=0.447 · | OntoSecAI=0.402 ·
  Perform Automated Vulnerability Scans of Internal Enterprise Assets      | D3FEND=0.592 ✓ | OntoSecAI=0.516 ✓
  Perform Automated Vulnerability Scans of Externally-Exposed Enterprise A | D3FEND=0.597 ✓ | OntoSecAI=0.506 ✓
  Remediate Detected Vulnerabilities                                       | D3FEND=0.445 · | OntoSecAI=0.505 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.7_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.8_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 25.88it/s]

  Retain Audit Logs                                                        | D3FEND=0.287 · | OntoSecAI=0.339 ·
  Collect Audit Logs                                                       | D3FEND=0.356 · | OntoSecAI=0.411 ·
  Ensure Adequate Audit Log Storage                                        | D3FEND=0.350 · | OntoSecAI=0.398 ·
  Standardize Time Synchronization                                         | D3FEND=0.235 · | OntoSecAI=0.154 ·
  Collect Detailed Audit Logs                                              | D3FEND=0.364 · | OntoSecAI=0.413 ·
  Collect DNS Query Audit Logs                                             | D3FEND=0.454 ✓ | OntoSecAI=0.427 ·
  Collect URL Request Audit Logs                                           | D3FEND=0.343 · | OntoSecAI=0.459 ✓
  Collect Command-Line Audit Logs                                          | D3FEND=0.368 · | OntoSecAI=0.339 ·
  Centralize Audit Logs                                                    | D3FEND=0.335 · | OntoSecAI=0.422 ·
  Conduct Audit Log Reviews                                                | D3FEND=0.333 · | OntoSecAI=0.373 ·
  Collect Service Provider Logs                                            | D3FEND=0.336 · | OntoSecAI=0.420 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.8_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.9_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 21.91it/s]

  Ensure Use of Only Fully Supported Browsers and Email Clients            | D3FEND=0.327 · | OntoSecAI=0.375 ·
  Use DNS Filtering Services                                               | D3FEND=0.719 ✓ | OntoSecAI=0.329 ·
  Maintain Network-Based URL Filters                                       | D3FEND=0.394 · | OntoSecAI=0.334 ·
  Enforce Network-Based URL Filters                                        | D3FEND=0.526 ✓ | OntoSecAI=0.435 ·
  Restrict Unnecessary or Unauthorized Browser and Email Client Extensions | D3FEND=0.370 · | OntoSecAI=0.418 ·
  Implement DMARC                                                          | D3FEND=0.391 · | OntoSecAI=0.296 ·
  Block Unnecessary File Types                                             | D3FEND=0.460 ✓ | OntoSecAI=0.370 ·
  Deploy Email Server Anti-Malware Protections                             | D3FEND=0.416 · | OntoSecAI=0.370 ·
  Maintain Email Server Anti-Malware Protections                           | D3FEND=0.392 · | OntoSecAI=0.333 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.9_leaf_goals_classified.operationalized_embeddings.json

==========================================================================================
AI-RMF — 4 goal-model files
==========================================================================================

Processing: E:\Shahin\iso2goalmodel\goal_models_AIRMF\GOVERN_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 14.34it/s]

  Establish organizational policies, processes, and procedures for mapping | D3FEND=0.467 ✓ | OntoSecAI=0.610 ✓
  Implement organizational policies, processes, and procedures for mapping | D3FEND=0.458 ✓ | OntoSecAI=0.600 ✓
  Maintain organizational policies, processes, and procedures for mapping, | D3FEND=0.462 ✓ | OntoSecAI=0.605 ✓
  Define roles and responsibilities for AI risk management                 | D3FEND=0.418 · | OntoSecAI=0.554 ✓
  Document roles and responsibilities for AI risk management               | D3FEND=0.363 · | OntoSecAI=0.527 ✓
  Understand roles and responsibilities for AI risk management             | D3FEND=0.376 · | OntoSecAI=0.549 ✓
  Integrate AI risk management into organizational culture and decision ma | D3FEND=0.404 · | OntoSecAI=0.458 ✓
  Establish processes to monitor compliance with laws, regulations, and et | D3FEND=0.362 · | OntoSecAI=0.281 ·
  Allocate resources for AI risk management activities                     | D3FEND=0.432 · | OntoSecAI=0.597 ✓
  Define processes for internal and external communication about AI risks  | D3FEND=0.411 · | OntoSecAI=0.579 ✓
  Implement processes for internal and external communication about AI ris | D3FEND=0.394 · | OntoSecAI=0.594 ✓
  Establish mechanisms for accountability and transparency related to AI s | D3FEND=0.337 · | OntoSecAI=0.583 ✓
Saved: E:\Shahin\iso2goalmodel\goal_models_AIRMF\GOVERN_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_AIRMF\MANAGE_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]

  Establish processes for prioritizing and responding to AI risks          | D3FEND=0.440 · | OntoSecAI=0.571 ✓
  Align processes for prioritizing and responding to AI risks with organiz | D3FEND=0.459 ✓ | OntoSecAI=0.548 ✓
  Develop AI risk treatment plans                                          | D3FEND=0.329 · | OntoSecAI=0.473 ✓
  Implement AI risk treatment plans                                        | D3FEND=0.344 · | OntoSecAI=0.503 ✓
  Maintain AI risk treatment plans                                         | D3FEND=0.322 · | OntoSecAI=0.475 ✓
  Establish plans for monitoring AI risks and for incident response and re | D3FEND=0.503 ✓ | OntoSecAI=0.612 ✓
  Establish processes for communicating AI risk information and decisions  | D3FEND=0.376 · | OntoSecAI=0.551 ✓
  Exceed processes for updating, remediating, or removing AI systems when  | D3FEND=0.390 · | OntoSecAI=0.548 ✓
  Establish processes for continual improvement of AI risk management      | D3FEND=0.409 · | OntoSecAI=0.582 ✓
  Ensure risk treatment decisions are based on prioritized risks, impact a | D3FEND=0.431 · | OntoSecAI=0.243 ·
  Select controls and mitigation actions                                   | D3FEND=0.364 · | OntoSecAI=0.389 ·
  Implement controls and mitigation actions to address identified risks    | D3FEND=0.467 ✓ | OntoSecAI=0.431 ·
  Document residual risks                                                  | D3FEND=0.331 · | OntoSecAI=0.325 ·
  Communicate residual risks                                               | D3FEND=0.340 · | OntoSecAI=0.366 ·
  Accept residual risks                                                    | D3FEND=0.249 · | OntoSecAI=0.223 ·
  Implement mechanisms for tracking the effectiveness of controls and for  | D3FEND=0.457 ✓ | OntoSecAI=0.372 ·
  Exercise incident response and recovery processes                        | D3FEND=0.177 · | OntoSecAI=0.088 ·
  Improve incident response and recovery processes using lessons learned   | D3FEND=0.331 · | OntoSecAI=0.243 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_AIRMF\MANAGE_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_AIRMF\MAP_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00,  4.83it/s]

  Understand intended purposes, beneficial uses, context-specific laws, no | D3FEND=0.365 · | OntoSecAI=0.340 ·
  Document intended purposes, beneficial uses, context-specific laws, norm | D3FEND=0.312 · | OntoSecAI=0.281 ·
  Ensure interdisciplinary AI actors, competencies, and participation refl | D3FEND=0.249 · | OntoSecAI=0.391 ·
  Understand the organization mission and relevant goals for AI technology | D3FEND=0.353 · | OntoSecAI=0.504 ✓
  Document the organization mission and relevant goals for AI technology   | D3FEND=0.341 · | OntoSecAI=0.519 ✓
  Define the business value or context of business use                     | D3FEND=0.321 · | OntoSecAI=0.235 ·
  Re-evaluate the business value or context of business use                | D3FEND=0.276 · | OntoSecAI=0.233 ·
  Determine organizational risk tolerances                                 | D3FEND=0.416 · | OntoSecAI=0.235 ·
  Document organizational risk tolerances                                  | D3FEND=0.349 · | OntoSecAI=0.318 ·
  Elicit system requirements and socio-technical implications are consider | D3FEND=0.284 · | OntoSecAI=0.361 ·
  Define the specific tasks and methods used to implement the tasks the AI | D3FEND=0.352 · | OntoSecAI=0.490 ✓
  Document information about knowledge limits and human oversight of the A | D3FEND=0.295 · | OntoSecAI=0.599 ✓
  Identify scientific integrity and TEVV considerations                    | D3FEND=0.359 · | OntoSecAI=0.400 ·
  Document scientific integrity and TEVV considerations                    | D3FEND=0.374 · | OntoSecAI=0.388 ·
  Examine potential benefits of intended AI system functionality and perfo | D3FEND=0.307 · | OntoSecAI=0.442 ·
  Document potential benefits of intended AI system functionality and perf | D3FEND=0.307 · | OntoSecAI=0.516 ✓
  Examine potential costs from expected or realized AI errors or functiona | D3FEND=0.290 · | OntoSecAI=0.421 ·
  Document potential costs from expected or realized AI errors or function | D3FEND=0.282 · | OntoSecAI=0.445 ·
  Specify targeted application scope                                       | D3FEND=0.371 · | OntoSecAI=0.425 ·
  Document targeted application scope based on system capability and conte | D3FEND=0.308 · | OntoSecAI=0.345 ·
  Define processes for operator and practitioner proficiency               | D3FEND=0.301 · | OntoSecAI=0.257 ·
  Assess processes for operator and practitioner proficiency               | D3FEND=0.264 · | OntoSecAI=0.217 ·
  Document processes for operator and practitioner proficiency             | D3FEND=0.284 · | OntoSecAI=0.221 ·
  Define processes for human oversight                                     | D3FEND=0.476 ✓ | OntoSecAI=0.443 ·
  Assess processes for human oversight                                     | D3FEND=0.432 · | OntoSecAI=0.382 ·
  Document processes for human oversight                                   | D3FEND=0.359 · | OntoSecAI=0.385 ·
  Document approaches for mapping AI technology and legal risks of compone | D3FEND=0.406 · | OntoSecAI=0.641 ✓
  Identify internal risk controls for components of the AI system, includi | D3FEND=0.483 ✓ | OntoSecAI=0.590 ✓
  Document internal risk controls for components of the AI system, includi | D3FEND=0.446 · | OntoSecAI=0.625 ✓
  Document likelihood and magnitude of each identified impact              | D3FEND=0.361 · | OntoSecAI=0.238 ·
  Ensure practices and personnel for supporting regular engagement with re | D3FEND=0.313 · | OntoSecAI=0.427 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_AIRMF\MAP_leaf_goals_classified.operationalized_embeddings.json

Processing: E:\Shahin\iso2goalmodel\goal_models_AIRMF\MEASURE_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00,  3.50it/s]

  Select approaches and metrics for measurement of AI risks for implementa | D3FEND=0.453 ✓ | OntoSecAI=0.577 ✓
  Assess appropriateness of AI metrics and effectiveness of existing contr | D3FEND=0.347 · | OntoSecAI=0.478 ✓
  Update appropriateness of AI metrics and effectiveness of existing contr | D3FEND=0.319 · | OntoSecAI=0.464 ✓
  Involve independent assessors and relevant stakeholders in regular asses | D3FEND=0.272 · | OntoSecAI=0.280 ·
  Document test sets, metrics, and details about the tools used during TEV | D3FEND=0.315 · | OntoSecAI=0.364 ·
  Ensure evaluations involving human subjects meet applicable requirements | D3FEND=0.214 · | OntoSecAI=0.313 ·
  Measure AI system performance or assurance criteria                      | D3FEND=0.395 · | OntoSecAI=0.514 ✓
  Document AI system performance or assurance criteria                     | D3FEND=0.304 · | OntoSecAI=0.464 ✓
  Monitor the functionality and behavior of the AI system and its componen | D3FEND=0.441 · | OntoSecAI=0.488 ✓
  Demonstrate the AI system to be deployed to be valid and reliable        | D3FEND=0.416 · | OntoSecAI=0.556 ✓
  Evaluate the AI system regularly for safety risks                        | D3FEND=0.407 · | OntoSecAI=0.536 ✓
  Demonstrate the AI system to be safe within risk tolerance               | D3FEND=0.374 · | OntoSecAI=0.588 ✓
  Evaluate AI system security and resilience                               | D3FEND=0.551 ✓ | OntoSecAI=0.669 ✓
  Document AI system security and resilience                               | D3FEND=0.413 · | OntoSecAI=0.570 ✓
  Examine risks associated with transparency and accountability            | D3FEND=0.264 · | OntoSecAI=0.272 ·
  Document risks associated with transparency and accountability           | D3FEND=0.292 · | OntoSecAI=0.335 ·
  Explain the AI model                                                     | D3FEND=0.331 · | OntoSecAI=0.429 ·
  Validate the AI model                                                    | D3FEND=0.335 · | OntoSecAI=0.570 ✓
  Document the AI model                                                    | D3FEND=0.300 · | OntoSecAI=0.444 ·
  Interpret output within context                                          | D3FEND=0.219 · | OntoSecAI=0.211 ·
  Examine privacy risk of the AI system                                    | D3FEND=0.392 · | OntoSecAI=0.663 ✓
  Document privacy risk of the AI system                                   | D3FEND=0.329 · | OntoSecAI=0.611 ✓
  Evaluate fairness and bias and results are documented                    | D3FEND=0.283 · | OntoSecAI=0.292 ·
  Assess environmental impact and sustainability                           | D3FEND=0.213 · | OntoSecAI=0.088 ·
  Document environmental impact and sustainability                         | D3FEND=0.258 · | OntoSecAI=0.102 ·
  Evaluate effectiveness of the TEVV metrics and processes                 | D3FEND=0.308 · | OntoSecAI=0.231 ·
  Document effectiveness of the TEVV metrics and processes                 | D3FEND=0.314 · | OntoSecAI=0.245 ·
  Ensure approaches, personnel, and documentation are in place to regularl | D3FEND=0.488 ✓ | OntoSecAI=0.406 ·
  Consider risk tracking approaches where AI risks are difficult to assess | D3FEND=0.418 · | OntoSecAI=0.490 ✓
  Establish feedback processes for end users and impacted communities      | D3FEND=0.232 · | OntoSecAI=0.216 ·
  Integrate feedback processes for end users and impacted communities into | D3FEND=0.243 · | OntoSecAI=0.190 ·
  Ensure measurement approaches are connected to deployment contexts and i | D3FEND=0.421 · | OntoSecAI=0.372 ·
  Inform measurement results to validate intended performance              | D3FEND=0.340 · | OntoSecAI=0.345 ·
  Identify measurable performance improvements or declines                 | D3FEND=0.336 · | OntoSecAI=0.190 ·
  Document measurable performance improvements or declines                 | D3FEND=0.334 · | OntoSecAI=0.161 ·
Saved: E:\Shahin\iso2goalmodel\goal_models_AIRMF\MEASURE_leaf_goals_classified.operationalized_embeddings.json

==============================================================================================================================================================================================
SUMMARY — PER JSON
==============================================================================================================================================================================================

[A.10.1_leaf_goals_classified.json]
Goals      : 6
Leaf goals : 4
ORG goals  : 0
PHYS goals : 0
TECH goals : 4
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 2
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 2

[A.11.1_leaf_goals_classified.json]
Goals      : 13
Leaf goals : 11
ORG goals  : 0
PHYS goals : 11
TECH goals : 0
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 10
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 6
  TECH operationalized OntoSecAI : 0

[A.5.1_leaf_goals_classified.json]
Goals      : 8
Leaf goals : 6
ORG goals  : 6
PHYS goals : 0
TECH goals : 0
  ORG operationalized D3FEND     : 3
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 3
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 0

[A.6.1_leaf_goals_classified.json]
Goals      : 8
Leaf goals : 6
ORG goals  : 6
PHYS goals : 0
TECH goals : 0
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 2
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 0

[A.6.2_leaf_goals_classified.json]
Goals      : 6
Leaf goals : 4
ORG goals  : 0
PHYS goals : 1
TECH goals : 3
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 2
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 2

[A.7.1_leaf_goals_classified.json]
Goals      : 4
Leaf goals : 2
ORG goals  : 2
PHYS goals : 0
TECH goals : 0
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 0

[A.7.2_leaf_goals_classified.json]
Goals      : 5
Leaf goals : 3
ORG goals  : 3
PHYS goals : 0
TECH goals : 0
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 0

[A.7.3_leaf_goals_classified.json]
Goals      : 5
Leaf goals : 3
ORG goals  : 3
PHYS goals : 0
TECH goals : 0
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 0

[A.8.1_leaf_goals_classified.json]
Goals      : 9
Leaf goals : 7
ORG goals  : 7
PHYS goals : 0
TECH goals : 0
  ORG operationalized D3FEND     : 2
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 1
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 0

[A.8.2_leaf_goals_classified.json]
Goals      : 7
Leaf goals : 5
ORG goals  : 5
PHYS goals : 0
TECH goals : 0
  ORG operationalized D3FEND     : 2
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 1
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 0

[A.8.3_leaf_goals_classified.json]
Goals      : 5
Leaf goals : 3
ORG goals  : 1
PHYS goals : 1
TECH goals : 1
  ORG operationalized D3FEND     : 1
  PHYS operationalized D3FEND    : 1
  TECH operationalized D3FEND    : 1
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 1
  TECH operationalized OntoSecAI : 0

[A.9.1_leaf_goals_classified.json]
Goals      : 6
Leaf goals : 4
ORG goals  : 1
PHYS goals : 1
TECH goals : 2
  ORG operationalized D3FEND     : 1
  PHYS operationalized D3FEND    : 1
  TECH operationalized D3FEND    : 2
  ORG operationalized OntoSecAI  : 1
  PHYS operationalized OntoSecAI : 1
  TECH operationalized OntoSecAI : 2

[A.9.2_leaf_goals_classified.json]
Goals      : 10
Leaf goals : 8
ORG goals  : 1
PHYS goals : 1
TECH goals : 6
  ORG operationalized D3FEND     : 1
  PHYS operationalized D3FEND    : 1
  TECH operationalized D3FEND    : 5
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 5

[A.9.3_leaf_goals_classified.json]
Goals      : 3
Leaf goals : 1
ORG goals  : 1
PHYS goals : 0
TECH goals : 0
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 1
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 0

[A.9.4_leaf_goals_classified.json]
Goals      : 7
Leaf goals : 5
ORG goals  : 0
PHYS goals : 0
TECH goals : 5
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 5
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 4

[A.10_leaf_goals_classified.json]
Goals      : 8
Leaf goals : 6
ORG goals  : 5
PHYS goals : 0
TECH goals : 1
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 0

[A.2_leaf_goals_classified.json]
Goals      : 5
Leaf goals : 3
ORG goals  : 3
PHYS goals : 0
TECH goals : 0
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 3
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 0

[A.3_leaf_goals_classified.json]
Goals      : 8
Leaf goals : 6
ORG goals  : 5
PHYS goals : 0
TECH goals : 1
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 3
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 1

[A.4_leaf_goals_classified.json]
Goals      : 7
Leaf goals : 5
ORG goals  : 3
PHYS goals : 0
TECH goals : 2
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 2
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 0

[A.5_leaf_goals_classified.json]
Goals      : 7
Leaf goals : 5
ORG goals  : 4
PHYS goals : 0
TECH goals : 1
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 1

[A.6_leaf_goals_classified.json]
Goals      : 10
Leaf goals : 8
ORG goals  : 1
PHYS goals : 0
TECH goals : 7
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 5

[A.7_leaf_goals_classified.json]
Goals      : 11
Leaf goals : 9
ORG goals  : 4
PHYS goals : 0
TECH goals : 5
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 2
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 2

[A.8_leaf_goals_classified.json]
Goals      : 6
Leaf goals : 4
ORG goals  : 3
PHYS goals : 0
TECH goals : 1
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 2
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 1

[A.9_leaf_goals_classified.json]
Goals      : 7
Leaf goals : 5
ORG goals  : 3
PHYS goals : 0
TECH goals : 2
  ORG operationalized D3FEND     : 1
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 1
  ORG operationalized OntoSecAI  : 2
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 2

[AC_leaf_goals_classified.json]
Goals      : 14
Leaf goals : 12
ORG goals  : 2
PHYS goals : 1
TECH goals : 9
  ORG operationalized D3FEND     : 2
  PHYS operationalized D3FEND    : 1
  TECH operationalized D3FEND    : 6
  ORG operationalized OntoSecAI  : 2
  PHYS operationalized OntoSecAI : 1
  TECH operationalized OntoSecAI : 6

[AU_leaf_goals_classified.json]
Goals      : 9
Leaf goals : 7
ORG goals  : 6
PHYS goals : 0
TECH goals : 1
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 1
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 1

[CA_leaf_goals_classified.json]
Goals      : 9
Leaf goals : 7
ORG goals  : 5
PHYS goals : 0
TECH goals : 2
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 2
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 1

[CM_leaf_goals_classified.json]
Goals      : 12
Leaf goals : 10
ORG goals  : 4
PHYS goals : 0
TECH goals : 6
  ORG operationalized D3FEND     : 3
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 2
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 1

[CP_leaf_goals_classified.json]
Goals      : 11
Leaf goals : 9
ORG goals  : 6
PHYS goals : 0
TECH goals : 3
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 1

[IA_leaf_goals_classified.json]
Goals      : 11
Leaf goals : 9
ORG goals  : 1
PHYS goals : 3
TECH goals : 5
  ORG operationalized D3FEND     : 1
  PHYS operationalized D3FEND    : 3
  TECH operationalized D3FEND    : 5
  ORG operationalized OntoSecAI  : 1
  PHYS operationalized OntoSecAI : 2
  TECH operationalized OntoSecAI : 3

[IR_leaf_goals_classified.json]
Goals      : 8
Leaf goals : 6
ORG goals  : 6
PHYS goals : 0
TECH goals : 0
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 1
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 0

[MA_leaf_goals_classified.json]
Goals      : 9
Leaf goals : 7
ORG goals  : 3
PHYS goals : 0
TECH goals : 4
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 2
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 0

[MP_leaf_goals_classified.json]
Goals      : 7
Leaf goals : 5
ORG goals  : 0
PHYS goals : 4
TECH goals : 1
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 4
  TECH operationalized D3FEND    : 1
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 1

[PE_leaf_goals_classified.json]
Goals      : 9
Leaf goals : 7
ORG goals  : 3
PHYS goals : 4
TECH goals : 0
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 4
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 4
  TECH operationalized OntoSecAI : 0

[PL_leaf_goals_classified.json]
Goals      : 6
Leaf goals : 4
ORG goals  : 3
PHYS goals : 0
TECH goals : 1
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 1
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 1

[PM_leaf_goals_classified.json]
Goals      : 6
Leaf goals : 4
ORG goals  : 3
PHYS goals : 1
TECH goals : 0
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 1
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 1
  TECH operationalized OntoSecAI : 0

[PS_leaf_goals_classified.json]
Goals      : 7
Leaf goals : 5
ORG goals  : 3
PHYS goals : 2
TECH goals : 0
  ORG operationalized D3FEND     : 3
  PHYS operationalized D3FEND    : 2
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 1
  TECH operationalized OntoSecAI : 0

[PT_leaf_goals_classified.json]
Goals      : 6
Leaf goals : 4
ORG goals  : 4
PHYS goals : 0
TECH goals : 0
  ORG operationalized D3FEND     : 2
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 2
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 0

[RA_leaf_goals_classified.json]
Goals      : 7
Leaf goals : 5
ORG goals  : 4
PHYS goals : 0
TECH goals : 1
  ORG operationalized D3FEND     : 2
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 1
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 0

[SA_leaf_goals_classified.json]
Goals      : 10
Leaf goals : 8
ORG goals  : 5
PHYS goals : 0
TECH goals : 3
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 3
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 2

[SC_leaf_goals_classified.json]
Goals      : 10
Leaf goals : 8
ORG goals  : 0
PHYS goals : 3
TECH goals : 5
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 2
  TECH operationalized D3FEND    : 3
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 2
  TECH operationalized OntoSecAI : 2

[SI_leaf_goals_classified.json]
Goals      : 10
Leaf goals : 8
ORG goals  : 4
PHYS goals : 0
TECH goals : 4
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 3
  ORG operationalized OntoSecAI  : 1
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 2

[SR_leaf_goals_classified.json]
Goals      : 9
Leaf goals : 7
ORG goals  : 7
PHYS goals : 0
TECH goals : 0
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 0
  ORG operationalized OntoSecAI  : 2
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 0

[CIS.10_leaf_goals_classified.json]
Goals      : 10
Leaf goals : 8
ORG goals  : 0
PHYS goals : 0
TECH goals : 8
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 3
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 2

[CIS.11_leaf_goals_classified.json]
Goals      : 9
Leaf goals : 7
ORG goals  : 1
PHYS goals : 0
TECH goals : 6
  ORG operationalized D3FEND     : 1
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 3
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 2

[CIS.12_leaf_goals_classified.json]
Goals      : 13
Leaf goals : 11
ORG goals  : 1
PHYS goals : 1
TECH goals : 9
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 6
  ORG operationalized OntoSecAI  : 0
  PHYS operationalized OntoSecAI : 0
  TECH operationalized OntoSecAI : 5

[CIS.13_leaf_goals_classified.json]
Goals      : 12
Leaf goals : 10
ORG goals  : 0
PHYS goals : 0
TECH goals : 10
  ORG operationalized D3FEND     : 0
  PHYS operationalized D3FEND    : 0
  TECH operationalized D3FEND    : 6
  ORG operationalized OntoSecAI  : 0

### Operationalization (using LLM) - Qwen3

In [6]:
# Ran the script with all goal models with a MAX_TOKENS=2000.
%run operationalization_via_qwen.py

Input directories:
  ISO 27001    -> E:\Shahin\iso2goalmodel\goal_models_ISO27001
  ISO 42001    -> E:\Shahin\iso2goalmodel\goal_models_ISO42001
  NIST         -> E:\Shahin\iso2goalmodel\goal_models_NIST
  CIS          -> E:\Shahin\iso2goalmodel\goal_models_CIS
  AI-RMF       -> E:\Shahin\iso2goalmodel\goal_models_AIRMF
Input pattern    : *_leaf_goals_classified.json
Loading D3FEND...
Loading OntoSecAI...

Knowledge-base index
------------------------------------------------------------
D3FEND defensive techniques : 271
OntoSecAI mitigations        : 81

Checking llama.cpp at http://127.0.0.1:11434/v1...
llama.cpp models: qwen3:8b

Loading embedding model: sentence-transformers/all-mpnet-base-v2

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1842.94it/s]

Encoding D3FEND techniques...

Batches: 100%|██████████| 5/5 [00:06<00:00,  1.38s/it]

Encoding OntoSecAI mitigations...

Batches: 100%|██████████| 2/2 [00:02<00:00,  1.25s/it]

==========================================================================================
ISO 27001 — 15 goal-model files
==========================================================================================

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.10.1_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.69it/s]

  Develop a policy on the use of cryptographic controls for protection of inf | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.49it/s]

  Implement a policy on the use of cryptographic controls for protection of i | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 63.21it/s]

  Develop a policy on the use, protection and lifetime of cryptographic keys  | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.48it/s]

  Implement a policy on the use, protection and lifetime of cryptographic key | D3FEND=✓ | OntoSecAI=· | actions=1
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.10.1_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.11.1_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.24it/s]

  Define security perimeters                                                  | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 49.61it/s]

  Use security perimeters to protect areas that contain either sensitive or c | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.02it/s]

  Protect secure areas to ensure that only authorized personnel are allowed a | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.50it/s]

  Design physical security for offices, rooms and facilities                  | D3FEND=✓ | OntoSecAI=· | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 50.86it/s]

  Apply physical security for offices, rooms and facilities                   | D3FEND=✓ | OntoSecAI=· | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.21it/s]

  Design physical protection against natural disasters, malicious attack or a | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.48it/s]

  Apply physical protection against natural disasters, malicious attack or ac | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.70it/s]

  Design procedures for working in secure areas                               | D3FEND=✓ | OntoSecAI=· | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.01it/s]

  Apply procedures for working in secure areas                                | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 50.84it/s]

  Control access points such as delivery and loading areas and other points w | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 50.80it/s]

  Isolate access points such as delivery and loading areas and other points w | D3FEND=✓ | OntoSecAI=· | actions=2
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.11.1_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.5.1_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.14it/s]

  Define a set of policies for information security                           | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.77it/s]

  Approve a set of policies for information security                          | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 65.56it/s]

  Publish a set of policies for information security                          | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.63it/s]

  Communicate a set of policies for information security to employees and rel | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.13it/s]

  Review the policies for information security at planned intervals to ensure | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 48.86it/s]

  Review the policies for information security if significant changes occur t | D3FEND=✓ | OntoSecAI=✓ | actions=3
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.5.1_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.6.1_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.35it/s]

  Define all information security responsibilities                            | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.56it/s]

  Allocate all information security responsibilities                          | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 48.25it/s]

  Segregate conflicting duties and areas of responsibility to reduce opportun | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.88it/s]

  Maintain appropriate contacts with relevant authorities                     | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.91it/s]

  Maintain appropriate contacts with special interest groups or other special | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.14it/s]

  Address information security in project management, regardless of the type  | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.6.1_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.6.2_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.00it/s]

  Adopt a policy and supporting security measures to manage the risks introdu | D3FEND=✓ | OntoSecAI=· | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.88it/s]

  Implement a policy and supporting security measures to protect information  | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.68it/s]

  Process a policy and supporting security measures                           | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.86it/s]

  Store a policy and supporting security measures at teleworking sites        | D3FEND=✓ | OntoSecAI=· | actions=1
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.6.2_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.7.1_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.06it/s]

  Carry out background verification checks on all candidates for employment i | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.93it/s]

  State their and the organization's responsibilities for information securit | D3FEND=✓ | OntoSecAI=✓ | actions=3
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.7.1_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.7.2_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 48.30it/s]

  Require all employees and contractors to apply information security in acco | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.55it/s]

  Receive appropriate awareness education and training and regular updates in | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.79it/s]

  Establish a formal and communicated disciplinary process in place to take a | D3FEND=· | OntoSecAI=· | actions=0
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.7.2_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.7.3_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.39it/s]

  Define information security responsibilities and duties that remain valid a | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 46.17it/s]

  Communicate information security responsibilities and duties that remain va | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.69it/s]

  Enforce information security responsibilities and duties that remain valid  | D3FEND=✓ | OntoSecAI=· | actions=2
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.7.3_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.8.1_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.21it/s]

  Identify assets associated with information and information processing faci | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.97it/s]

  Maintain assets associated with information and information processing faci | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.50it/s]

  Ensure assets maintained in the inventory are owned                         | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.47it/s]

  Identify rules for the acceptable use of information and of assets associat | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.04it/s]

  Document rules for the acceptable use of information and of assets associat | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.39it/s]

  Implement rules for the acceptable use of information and of assets associa | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.66it/s]

  Return all of the organizational assets in their possession upon terminatio | D3FEND=· | OntoSecAI=· | actions=0
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.8.1_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.8.2_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.74it/s]

  Classify information in terms of legal requirements, value, criticality and | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.63it/s]

  Develop an appropriate set of procedures for information labelling          | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.71it/s]

  Implement an appropriate set of procedures for information labelling in acc | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.36it/s]

  Develop procedures for handling assets                                      | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.75it/s]

  Implement procedures for handling assets in accordance with the information | D3FEND=✓ | OntoSecAI=✓ | actions=2
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.8.2_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.8.3_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.69it/s]

  Implement procedures for the management of removable media in accordance wi | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.58it/s]

  Dispose of media securely when no longer required, using formal procedures  | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.29it/s]

  Protect media containing information against unauthorized access, misuse or | D3FEND=✓ | OntoSecAI=✓ | actions=3
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.8.3_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.9.1_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.98it/s]

  Establish an access control policy                                          | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.85it/s]

  Document an access control policy                                           | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.38it/s]

  Review an access control policy based on business and information security  | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.39it/s]

  Only be provided with access to the network and network services that they  | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.9.1_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.9.2_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 49.83it/s]

  Implement a formal user registration and de-registration process to enable  | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 49.63it/s]

  Implement a formal user access provisioning process to assign or revoke acc | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.30it/s]

  Restrict the allocation and use of privileged access rights                 | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.80it/s]

  Control the allocation and use of privileged access rights                  | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.22it/s]

  Control the allocation of secret authentication information through a forma | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.42it/s]

  Review users' access rights at regular intervals                            | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.57it/s]

  Remove the access rights of all employees and external party users to infor | D3FEND=✓ | OntoSecAI=· | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.76it/s]

  Adjust the access rights of all employees and external party users to infor | D3FEND=✓ | OntoSecAI=✓ | actions=3
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.9.2_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.9.3_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.69it/s]

  Require users to follow the organization's practices in the use of secret a | D3FEND=✓ | OntoSecAI=✓ | actions=3
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.9.3_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.9.4_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.12it/s]

  Restrict access to information and application system functions in accordan | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.57it/s]

  Control where required by the access control policy, access to systems and  | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.02it/s]

  Ensure password management systems are interactive and shall ensure quality | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.76it/s]

  Restrict the use of utility programs that might be capable of overriding sy | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.82it/s]

  Restrict access to program source code                                      | D3FEND=✓ | OntoSecAI=✓ | actions=4
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO27001\A.9.4_leaf_goals_classified.operationalized_qwen.json

==========================================================================================
ISO 42001 — 9 goal-model files
==========================================================================================

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.10_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.60it/s]

  Define requirements for suppliers and external providers                    | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.38it/s]

  Identify requirements from customers and users                              | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.14it/s]

  Address requirements from customers and users                               | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.76it/s]

  Monitor Third-party relationships                                           | D3FEND=· | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.25it/s]

  Review Third-party relationships                                            | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.19it/s]

  Establish appropriate contractual controls                                  | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.10_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.2_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.84it/s]

  Establish an AI policy                                                      | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.22it/s]

  Align the AI policy with other relevant organizational policies             | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.27it/s]

  Review the AI policy at planned intervals and when significant changes occu | D3FEND=· | OntoSecAI=· | actions=0
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.2_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.3_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.06it/s]

  Define roles and responsibilities for AI                                    | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.29it/s]

  Assign roles and responsibilities for AI                                    | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.01it/s]

  Report AI issues                                                            | D3FEND=· | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.67it/s]

  Escalate AI issues                                                          | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.22it/s]

  Address AI issues                                                           | D3FEND=· | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 68.02it/s]

  Define responsibilities toward affected interested parties                  | D3FEND=✓ | OntoSecAI=✓ | actions=4
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.3_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.4_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.03it/s]

  Determine appropriate resources for AI systems                              | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 65.42it/s]

  Provide appropriate resources for AI systems                                | D3FEND=· | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.24it/s]

  Establish competence required for AI-related roles                          | D3FEND=· | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.01it/s]

  Maintain competence required for AI-related roles                           | D3FEND=· | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.10it/s]

  Ensure personnel are aware of AI policy, risks, and responsibilities        | D3FEND=· | OntoSecAI=· | actions=0
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.4_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.5_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.19it/s]

  Perform impact assessments for AI systems                                   | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.53it/s]

  Perform impact assessments at appropriate times across the AI lifecycle     | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.90it/s]

  Review impact assessment results                                            | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.80it/s]

  Update impact assessment results when needed                                | D3FEND=· | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.18it/s]

  Retain records of impact assessments                                        | D3FEND=✓ | OntoSecAI=✓ | actions=2
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.5_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.6_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 68.06it/s]

  Design AI systems                                                           | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.84it/s]

  Develop AI systems according to defined requirements                        | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.32it/s]

  Verify AI systems                                                           | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.75it/s]

  Validate AI systems before use                                              | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.87it/s]

  Control deployment of AI systems                                            | D3FEND=· | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.33it/s]

  Operate AI systems                                                          | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.65it/s]

  Monitor AI systems                                                          | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.44it/s]

  Maintain AI systems over their lifecycle                                    | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.6_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.7_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.55it/s]

  Acquire data used for AI systems appropriately                              | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.78it/s]

  Define data quality requirements                                            | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 63.11it/s]

  Check data quality requirements                                             | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.47it/s]

  Control data preparation activities                                         | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.88it/s]

  Track data provenance                                                       | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.89it/s]

  Maintain data provenance                                                    | D3FEND=✓ | OntoSecAI=· | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.97it/s]

  Define data selection criteria                                              | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.35it/s]

  Apply data selection criteria                                               | D3FEND=· | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.45it/s]

  Handle data securely and appropriately                                      | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.7_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.8_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.18it/s]

  Provide relevant information about AI systems to interested parties         | D3FEND=· | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 65.88it/s]

  Support transparency of AI system behavior                                  | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 65.88it/s]

  Make appropriate explainability information available                       | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.92it/s]

  Receive guidance for the intended use of AI systems                         | D3FEND=· | OntoSecAI=✓ | actions=4
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.8_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.9_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.98it/s]

  Use AI systems responsibly                                                  | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.85it/s]

  Define human oversight                                                      | D3FEND=· | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.42it/s]

  Implement human oversight                                                   | D3FEND=· | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.02it/s]

  Monitor use of AI systems for unintended behavior                           | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.94it/s]

  Monitor inputs and outputs of AI systems as needed                          | D3FEND=✓ | OntoSecAI=✓ | actions=4
Saved: E:\Shahin\iso2goalmodel\goal_models_ISO42001\A.9_leaf_goals_classified.operationalized_qwen.json

==========================================================================================
NIST — 19 goal-model files
==========================================================================================

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\AC_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.22it/s]

  Develop policy and procedures to facilitate the implementation of access co | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.58it/s]

  Document policy and procedures to facilitate the implementation of access c | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.14it/s]

  Disseminate policy and procedures to facilitate the implementation of acces | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.67it/s]

  Manage information system accounts, including establishing, activating, mod | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.25it/s]

  Enforce approved authorizations for logical access to information and syste | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.87it/s]

  Enforce approved authorizations for controlling information flow within the | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.46it/s]

  Separate duties and responsibilities to reduce opportunities for unauthoriz | D3FEND=· | OntoSecAI=· | actions=0
      warning: LLM error: Could not parse JSON object from model output: ''

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.54it/s]

  Employ the principle of least privilege, allowing only authorized accesses  | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.06it/s]

  Enforce a limit on consecutive invalid logon attempts by a user during a ti | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.87it/s]

  Display an approved system use notification message before granting access  | D3FEND=· | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.85it/s]

  Prevent further access to the system by initiating a device lock after defi | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.54it/s]

  Terminate a user session after a condition of inactivity or upon user logou | D3FEND=· | OntoSecAI=· | actions=0
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\AC_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\AU_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.64it/s]

  Develop policy and procedures to facilitate implementation of audit and acc | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.97it/s]

  Document policy and procedures to facilitate implementation of audit and ac | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.75it/s]

  Disseminate policy and procedures to facilitate implementation of audit and | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.02it/s]

  Determine that the information system can log events relevant to security m | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.21it/s]

  Generate audit records containing information sufficient to support monitor | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.59it/s]

  Allocate audit record storage capacity to store audit records for the defin | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.18it/s]

  Respond to audit logging process failures by taking appropriate action      | D3FEND=✓ | OntoSecAI=✓ | actions=2
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\AU_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\CA_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.30it/s]

  Develop policy and procedures to facilitate implementation of assessment, a | D3FEND=· | OntoSecAI=· | actions=0
      warning: LLM error: Could not parse JSON object from model output: ''

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.63it/s]

  Document policy and procedures to facilitate implementation of assessment,  | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.46it/s]

  Disseminate policy and procedures to facilitate implementation of assessmen | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.48it/s]

  Assess the controls in the system and environment of operation to determine | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.23it/s]

  Authorize connections and information exchange between systems using interc | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.77it/s]

  Develop a plan of action and milestones for the system                      | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.34it/s]

  Implement a plan of action and milestones for the system                    | D3FEND=✓ | OntoSecAI=✓ | actions=3
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\CA_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\CM_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.83it/s]

  Develop policy and procedures to facilitate implementation of configuration | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.46it/s]

  Document policy and procedures to facilitate implementation of configuratio | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.06it/s]

  Disseminate policy and procedures to facilitate implementation of configura | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.25it/s]

  Develop a current baseline configuration of the system                      | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.35it/s]

  Document a current baseline configuration of the system                     | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.50it/s]

  Maintain a current baseline configuration of the system                     | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.19it/s]

  Document changes to the system                                              | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.61it/s]

  Approve changes to the system                                               | D3FEND=· | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.07it/s]

  Monitor changes to the system                                               | D3FEND=✓ | OntoSecAI=· | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.49it/s]

  Analyze changes to the system to determine potential security impact prior  | D3FEND=✓ | OntoSecAI=· | actions=4
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\CM_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\CP_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.31it/s]

  Develop policy and procedures to facilitate implementation of contingency p | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.41it/s]

  Document policy and procedures to facilitate implementation of contingency  | D3FEND=· | OntoSecAI=· | actions=0
      warning: LLM error: Could not parse JSON object from model output: ''

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.62it/s]

  Disseminate policy and procedures to facilitate implementation of contingen | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.66it/s]

  Develop a contingency plan for the system                                   | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.86it/s]

  Document a contingency plan for the system                                  | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.10it/s]

  Maintain a contingency plan for the system                                  | D3FEND=· | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 63.51it/s]

  Provide contingency training to system users and personnel                  | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.31it/s]

  Test contingency plans for the system                                       | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.16it/s]

  Conduct backups of user-level and system-level information                  | D3FEND=· | OntoSecAI=✓ | actions=1
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\CP_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\IA_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.37it/s]

  Develop policy and procedures to facilitate implementation of identificatio | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.94it/s]

  Document policy and procedures to facilitate implementation of identificati | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.18it/s]

  Disseminate policy and procedures to facilitate implementation of identific | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.71it/s]

  Uniquely identify organizational users, processes acting on behalf of users | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.80it/s]

  Uniquely authenticate organizational users, processes acting on behalf of u | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.90it/s]

  Uniquely identify devices before establishing a connection                  | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.10it/s]

  Uniquely authenticate devices before establishing a connection              | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 48.54it/s]

  Manage user identifiers by, for example, disabling inactive identifiers and | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 49.17it/s]

  Manage information system authenticators by defining initial content, chang | D3FEND=✓ | OntoSecAI=· | actions=4
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\IA_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\IR_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.99it/s]

  Develop policy and procedures to facilitate incident response controls      | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.33it/s]

  Document policy and procedures to facilitate incident response controls     | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.36it/s]

  Disseminate policy and procedures to facilitate incident response controls  | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.35it/s]

  Provide incident response training to personnel with incident response role | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.96it/s]

  Test the incident response capability                                       | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.29it/s]

  Implement an incident handling capability for security incidents            | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\IR_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\MA_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.04it/s]

  Develop policy and procedures to facilitate maintenance controls            | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.62it/s]

  Document policy and procedures to facilitate maintenance controls           | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.30it/s]

  Disseminate policy and procedures to facilitate maintenance controls        | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.39it/s]

  Perform maintenance on system components in a controlled manner             | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.97it/s]

  Approve maintenance tools                                                   | D3FEND=· | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.28it/s]

  Control maintenance tools                                                   | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.29it/s]

  Monitor maintenance tools                                                   | D3FEND=✓ | OntoSecAI=· | actions=1
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\MA_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\MP_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.55it/s]

  Develop policy and procedures to facilitate media protection controls       | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.39it/s]

  Document policy and procedures to facilitate media protection controls      | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.84it/s]

  Disseminate policy and procedures to facilitate media protection controls   | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.99it/s]

  Restrict access to digital and non-digital media containing information     | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 49.22it/s]

  Protect information system media until the media are destroyed or sanitized | D3FEND=✓ | OntoSecAI=✓ | actions=2
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\MP_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\PE_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.57it/s]

  Develop policy and procedures to facilitate physical and environmental prot | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 63.42it/s]

  Document policy and procedures to facilitate physical and environmental pro | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.40it/s]

  Disseminate policy and procedures to facilitate physical and environmental  | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.78it/s]

  Develop physical access authorizations for designated areas                 | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.83it/s]

  Maintain physical access authorizations for designated areas                | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.37it/s]

  Enforce physical access control to the facility and areas within the facili | D3FEND=✓ | OntoSecAI=· | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.72it/s]

  Monitor physical access to the facility and physical areas containing syste | D3FEND=✓ | OntoSecAI=· | actions=4
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\PE_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\PL_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.44it/s]

  Develop policy and procedures to facilitate planning controls               | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.63it/s]

  Document policy and procedures to facilitate planning controls              | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.86it/s]

  Disseminate policy and procedures to facilitate planning controls           | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.33it/s]

  Develop system security and privacy plans that describe the system boundary | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\PL_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\PM_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.46it/s]

  Develop an organization-wide information security program plan              | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.16it/s]

  Document an organization-wide information security program plan             | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.62it/s]

  Disseminate an organization-wide information security program plan          | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.60it/s]

  Plan for and allocate security and privacy resources                        | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\PM_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\PS_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.41it/s]

  Develop policy and procedures to facilitate personnel security controls     | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.26it/s]

  Document policy and procedures to facilitate personnel security controls    | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.46it/s]

  Disseminate policy and procedures to facilitate personnel security controls | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.60it/s]

  Assign a risk designation to organizational positions                       | D3FEND=✓ | OntoSecAI=· | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.18it/s]

  Screen individuals prior to authorizing access to the information system    | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\PS_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\PT_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.58it/s]

  Develop policy and procedures to facilitate privacy controls                | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.85it/s]

  Document policy and procedures to facilitate privacy controls               | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.57it/s]

  Disseminate policy and procedures to facilitate privacy controls            | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.86it/s]

  Determine the legal authority and other requirements to process personally  | D3FEND=· | OntoSecAI=✓ | actions=3
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\PT_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\RA_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.63it/s]

  Develop policy and procedures to facilitate risk assessment controls        | D3FEND=✓ | OntoSecAI=· | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.97it/s]

  Document policy and procedures to facilitate risk assessment controls       | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.57it/s]

  Disseminate policy and procedures to facilitate risk assessment controls    | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.32it/s]

  Categorize the system and information processed, stored, and transmitted by | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 47.84it/s]

  Conduct a risk assessment to determine the risk to organizational operation | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\RA_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\SA_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.67it/s]

  Develop policy and procedures to facilitate system and services acquisition | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.97it/s]

  Document policy and procedures to facilitate system and services acquisitio | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.90it/s]

  Disseminate policy and procedures to facilitate system and services acquisi | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.80it/s]

  Determine resources required to protect the system                          | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.06it/s]

  Document resources required to protect the system                           | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.52it/s]

  Allocate resources required to protect the system                           | D3FEND=· | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.05it/s]

  Manage the system using a system development life cycle                     | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.20it/s]

  Include security and privacy requirements in acquisition contracts and rela | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\SA_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\SC_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.72it/s]

  Develop policy and procedures to facilitate system and communications prote | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.15it/s]

  Document policy and procedures to facilitate system and communications prot | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.01it/s]

  Disseminate policy and procedures to facilitate system and communications p | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.48it/s]

  Monitor communications at external boundaries and key internal boundaries   | D3FEND=✓ | OntoSecAI=· | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.32it/s]

  Control communications at external boundaries and key internal boundaries   | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.44it/s]

  Protect the confidentiality and integrity of transmitted information        | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.77it/s]

  Establish cryptographic keys for the system                                 | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.49it/s]

  Manage cryptographic keys for the system                                    | D3FEND=✓ | OntoSecAI=· | actions=1
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\SC_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\SI_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 49.69it/s]

  Develop policy and procedures to facilitate system and information integrit | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 48.35it/s]

  Document policy and procedures to facilitate system and information integri | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.09it/s]

  Disseminate policy and procedures to facilitate system and information inte | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.69it/s]

  Identify system flaws in a timely manner                                    | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.38it/s]

  Report system flaws in a timely manner                                      | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.84it/s]

  Correct system flaws in a timely manner                                     | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.89it/s]

  Implement malicious code protection mechanisms at system entry and exit poi | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 63.66it/s]

  Monitor the system to detect attacks and indicators of potential attacks    | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\SI_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_NIST\SR_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 63.04it/s]

  Develop policy and procedures to facilitate supply chain risk management co | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 63.88it/s]

  Document policy and procedures to facilitate supply chain risk management c | D3FEND=· | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.03it/s]

  Disseminate policy and procedures to facilitate supply chain risk managemen | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.63it/s]

  Develop a supply chain risk management plan for the system, system componen | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.35it/s]

  Establish controls and processes for managing supply chain risks            | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.63it/s]

  Document controls and processes for managing supply chain risks             | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.54it/s]

  Implement controls and processes for managing supply chain risks            | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_NIST\SR_leaf_goals_classified.operationalized_qwen.json

==========================================================================================
CIS — 18 goal-model files
==========================================================================================

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.10_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 63.15it/s]

  Deploy Anti-Malware Software                                                | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 65.22it/s]

  Maintain Anti-Malware Software                                              | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.35it/s]

  Configure Automatic Anti-Malware Signature Updates                          | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.00it/s]

  Disable Autorun and Autoplay for Removable Media                            | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.28it/s]

  Configure Automatic Anti-Malware Scanning of Removable Media                | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.04it/s]

  Enable Anti-Exploitation Features                                           | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.80it/s]

  Centrally Manage Anti-Malware Software                                      | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.13it/s]

  Use Behavior-Based Anti-Malware Software                                    | D3FEND=✓ | OntoSecAI=✓ | actions=2
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.10_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.11_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.88it/s]

  Establish a Data Recovery Process                                           | D3FEND=· | OntoSecAI=· | actions=0
      warning: LLM error: Could not parse JSON object from model output: ''

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.83it/s]

  Maintain a Data Recovery Process                                            | D3FEND=✓ | OntoSecAI=· | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 66.92it/s]

  Perform Automated Backups                                                   | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.19it/s]

  Protect Recovery Data                                                       | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.21it/s]

  Establish an Isolated Instance of Recovery Data                             | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.70it/s]

  Maintain an Isolated Instance of Recovery Data                              | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.11it/s]

  Test Data Recovery                                                          | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.11_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.12_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.13it/s]

  Ensure Network Infrastructure is Up-to-Date                                 | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.92it/s]

  Establish a Secure Network Architecture                                     | D3FEND=✓ | OntoSecAI=· | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.82it/s]

  Maintain a Secure Network Architecture                                      | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.76it/s]

  Securely Manage Network Infrastructure                                      | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.24it/s]

  Establish Architecture Diagram(s)                                           | D3FEND=✓ | OntoSecAI=· | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.85it/s]

  Maintain Architecture Diagram(s)                                            | D3FEND=· | OntoSecAI=· | actions=0
      warning: LLM error: Could not parse JSON object from model output: ''

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.69it/s]

  Centralize Network Authentication, Authorization, and Auditing (AAA)        | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.10it/s]

  Use of Secure Network Management and Communication Protocols                | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.52it/s]

  Ensure Remote Devices Utilize a VPN and are Connecting to an Enterprise’s A | D3FEND=✓ | OntoSecAI=· | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.16it/s]

  Establish Dedicated Computing Resources for All Administrative Work         | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.55it/s]

  Maintain Dedicated Computing Resources for All Administrative Work          | D3FEND=✓ | OntoSecAI=✓ | actions=3
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.12_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.13_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.28it/s]

  Perform Application Layer Filtering                                         | D3FEND=· | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.84it/s]

  Deploy a Host-Based Intrusion Detection Solution                            | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 66.67it/s]

  Deploy a Network Intrusion Detection Solution                               | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.09it/s]

  Perform Traffic Filtering Between Network Segments                          | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.07it/s]

  Manage Access Control for Remote Assets                                     | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.45it/s]

  Collect Network Traffic Flow Logs                                           | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.68it/s]

  Deploy a Host-Based Intrusion Prevention Solution                           | D3FEND=✓ | OntoSecAI=· | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 66.71it/s]

  Deploy a Network Intrusion Prevention Solution                              | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.00it/s]

  Deploy Port-Level Access Control                                            | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.88it/s]

  Ensure tune Security Event Alerting Thresholds                              | D3FEND=✓ | OntoSecAI=· | actions=2
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.13_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.14_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.36it/s]

  Establish a Security Awareness Program                                      | D3FEND=· | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.85it/s]

  Maintain a Security Awareness Program                                       | D3FEND=· | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.62it/s]

  Train Workforce Members to Recognize Social Engineering Attacks             | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.01it/s]

  Train Workforce Members on Authentication Best Practices                    | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.81it/s]

  Train Workforce on Data Handling Best Practices                             | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.61it/s]

  Train Workforce Members on Causes of Unintentional Data Exposure            | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.45it/s]

  Train Workforce Members on Recognizing and Reporting Security Incidents     | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.02it/s]

  Train Workforce on How to Identify and Report if Their Enterprise Assets ar | D3FEND=· | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.94it/s]

  Train Workforce on the Dangers of Connecting to and Transmitting Enterprise | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.60it/s]

  Conduct Role-Specific Security Awareness and Skills Training                | D3FEND=✓ | OntoSecAI=✓ | actions=2
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.14_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.15_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.43it/s]

  Establish an Inventory of Service Providers                                 | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.32it/s]

  Maintain an Inventory of Service Providers                                  | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.38it/s]

  Establish a Service Provider Management Policy                              | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.06it/s]

  Maintain a Service Provider Management Policy                               | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 66.20it/s]

  Classify Service Providers                                                  | D3FEND=✓ | OntoSecAI=· | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 46.64it/s]

  Ensure Service Provider Contracts Include Security Requirements             | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 66.11it/s]

  Assess Service Providers                                                    | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 65.55it/s]

  Monitor Service Providers                                                   | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.10it/s]

  Securely Decommission Service Providers                                     | D3FEND=✓ | OntoSecAI=· | actions=3
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.15_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.16_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.81it/s]

  Apply Secure Design Principles in Application Architectures                 | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.55it/s]

  Establish a Process to Accept and Address Software Vulnerabilities          | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.30it/s]

  Maintain a Process to Accept and Address Software Vulnerabilities           | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 67.58it/s]

  Perform Root Cause Analysis on Security Vulnerabilities                     | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.06it/s]

  Establish an Inventory of Third-Party Software Components                   | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.69it/s]

  Manage an Inventory of Third-Party Software Components                      | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.88it/s]

  Use Up-to-Date and Trusted Third-Party Software Components                  | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.93it/s]

  Establish a Severity Rating System and Process for Application Vulnerabilit | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.74it/s]

  Maintain a Severity Rating System and Process for Application Vulnerabiliti | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.55it/s]

  Use Standard Hardening Configuration Templates for Application Infrastructu | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.58it/s]

  Separate Production and Non-Production Systems                              | D3FEND=· | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.76it/s]

  Train Developers in Application Security Concepts and Secure Coding         | D3FEND=· | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.43it/s]

  Ensure leverage Vetted Modules or Services for Application Security Compone | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 63.37it/s]

  Implement Code-Level Security Checks                                        | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.86it/s]

  Conduct Application Penetration Testing                                     | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.36it/s]

  Conduct Threat Modeling                                                     | D3FEND=✓ | OntoSecAI=· | actions=2
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.16_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.17_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.65it/s]

  Designate Personnel to Manage Incident Handling                             | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.27it/s]

  Establish Contact Information for Reporting Security Incidents              | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.12it/s]

  Maintain Contact Information for Reporting Security Incidents               | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.88it/s]

  Establish an Enterprise Process for Reporting Incidents                     | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.62it/s]

  Maintain an Enterprise Process for Reporting Incidents                      | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.36it/s]

  Establish an Incident Response Process                                      | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.01it/s]

  Maintain an Incident Response Process                                       | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.66it/s]

  Assign Key Roles and Responsibilities                                       | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.09it/s]

  Define Mechanisms for Communicating During Incident Response                | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.68it/s]

  Conduct Routine Incident Response Exercises                                 | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.56it/s]

  Conduct Post-Incident Reviews                                               | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.34it/s]

  Establish Security Incident Thresholds                                      | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.44it/s]

  Maintain Security Incident Thresholds                                       | D3FEND=✓ | OntoSecAI=· | actions=2
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.17_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.18_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.95it/s]

  Establish a Penetration Testing Program                                     | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.88it/s]

  Maintain a Penetration Testing Program                                      | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.38it/s]

  Perform Periodic External Penetration Tests                                 | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 65.28it/s]

  Remediate Penetration Test Findings                                         | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 66.61it/s]

  Validate Security Measures                                                  | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.37it/s]

  Perform Periodic Internal Penetration Tests                                 | D3FEND=✓ | OntoSecAI=✓ | actions=3
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.18_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.1_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.10it/s]

  Establish Detailed Enterprise Asset Inventory                               | D3FEND=· | OntoSecAI=· | actions=0
      warning: LLM error: Could not parse JSON object from model output: ''

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.68it/s]

  Maintain Detailed Enterprise Asset Inventory                                | D3FEND=✓ | OntoSecAI=· | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.66it/s]

  Address Unauthorized Assets                                                 | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.93it/s]

  Utilize an Active Discovery Tool                                            | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.53it/s]

  Use Dynamic Host Configuration Protocol (DHCP) Logging to Update Enterprise | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.37it/s]

  Use a Passive Asset Discovery Tool                                          | D3FEND=· | OntoSecAI=✓ | actions=1
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.1_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.2_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.69it/s]

  Establish a Software Inventory                                              | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.87it/s]

  Maintain a Software Inventory                                               | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 65.57it/s]

  Ensure Authorized Software is Currently Supported                           | D3FEND=· | OntoSecAI=· | actions=0
      warning: LLM error: Could not parse JSON object from model output: ''

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.41it/s]

  Address Unauthorized Software                                               | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.94it/s]

  Utilize Automated Software Inventory Tools                                  | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.36it/s]

  Allowlist Authorized Software                                               | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.65it/s]

  Allowlist Authorized Libraries                                              | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.84it/s]

  Allowlist Authorized Scripts                                                | D3FEND=✓ | OntoSecAI=· | actions=1
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.2_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.3_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.74it/s]

  Encrypt Sensitive Data in Transit                                           | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.53it/s]

  Establish a Data Inventory                                                  | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.37it/s]

  Maintain a Data Inventory                                                   | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.06it/s]

  Configure Data Access Control Lists                                         | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 63.05it/s]

  Enforce Data Retention                                                      | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.19it/s]

  Securely Dispose of Data                                                    | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.74it/s]

  Encrypt Data on End-User Devices                                            | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.12it/s]

  Establish a Data Classification Scheme                                      | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.92it/s]

  Maintain a Data Classification Scheme                                       | D3FEND=✓ | OntoSecAI=· | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 67.21it/s]

  Document Data Flows                                                         | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.78it/s]

  Encrypt Data on Removable Media                                             | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.19it/s]

  Encrypt Sensitive Data at Rest                                              | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.52it/s]

  Segment Data Processing and Storage Based on Sensitivity                    | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.80it/s]

  Deploy a Data Loss Prevention Solution                                      | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.81it/s]

  Log Sensitive Data Access                                                   | D3FEND=· | OntoSecAI=✓ | actions=1
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.3_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.4_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.79it/s]

  Enforce Automatic Device Lockout on Portable End-User Devices               | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.57it/s]

  Establish a Secure Configuration Process for Network Infrastructure         | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.19it/s]

  Maintain a Secure Configuration Process for Network Infrastructure          | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.67it/s]

  Configure Automatic Session Locking on Enterprise Assets                    | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 63.27it/s]

  Implement a Firewall on Servers                                             | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 66.46it/s]

  Manage a Firewall on Servers                                                | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.74it/s]

  Implement a Firewall on End-User Devices                                    | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 50.18it/s]

  Manage a Firewall on End-User Devices                                       | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.58it/s]

  Securely Manage Enterprise Assets and Software                              | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.20it/s]

  Manage Default Accounts on Enterprise Assets and Software                   | D3FEND=✓ | OntoSecAI=· | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.21it/s]

  Uninstall Unnecessary Services on Enterprise Assets and Software            | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.90it/s]

  Disable Unnecessary Services on Enterprise Assets and Software              | D3FEND=✓ | OntoSecAI=· | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.83it/s]

  Configure Trusted DNS Servers on Enterprise Assets                          | D3FEND=✓ | OntoSecAI=· | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.12it/s]

  Enforce Remote Wipe Capability on Portable End-User Devices                 | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.81it/s]

  Separate Enterprise Workspaces on Mobile End-User Devices                   | D3FEND=✓ | OntoSecAI=✓ | actions=2
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.4_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.5_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.11it/s]

  Establish an Inventory of Accounts                                          | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.85it/s]

  Maintain an Inventory of Accounts                                           | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.22it/s]

  Use Unique Passwords                                                        | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.76it/s]

  Disable Dormant Accounts                                                    | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.17it/s]

  Restrict Administrator Privileges to Dedicated Administrator Accounts       | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.91it/s]

  Establish an Inventory of Service Accounts                                  | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 69.07it/s]

  Maintain an Inventory of Service Accounts                                   | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.26it/s]

  Centralize Account Management                                               | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.5_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.6_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.32it/s]

  Establish an Access Granting Process                                        | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 63.74it/s]

  Establish an Access Revoking Process                                        | D3FEND=✓ | OntoSecAI=· | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.61it/s]

  Require MFA for Externally-Exposed Applications                             | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 66.94it/s]

  Require MFA for Remote Network Access                                       | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.67it/s]

  Require MFA for Administrative Access                                       | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.03it/s]

  Establish an Inventory of Authentication and Authorization Systems          | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.79it/s]

  Maintain an Inventory of Authentication and Authorization Systems           | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.91it/s]

  Centralize Access Control                                                   | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.32it/s]

  Define Role-Based Access Control                                            | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 65.01it/s]

  Maintain Role-Based Access Control                                          | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.6_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.7_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.33it/s]

  Establish a Vulnerability Management Process                                | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.81it/s]

  Maintain a Vulnerability Management Process                                 | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.29it/s]

  Establish a Remediation Process                                             | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.05it/s]

  Maintain a Remediation Process                                              | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 65.01it/s]

  Perform Automated Operating System Patch Management                         | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.76it/s]

  Perform Automated Application Patch Management                              | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.60it/s]

  Perform Automated Vulnerability Scans of Internal Enterprise Assets         | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.89it/s]

  Perform Automated Vulnerability Scans of Externally-Exposed Enterprise Asse | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.53it/s]

  Remediate Detected Vulnerabilities                                          | D3FEND=✓ | OntoSecAI=✓ | actions=4
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.7_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.8_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.11it/s]

  Retain Audit Logs                                                           | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.11it/s]

  Collect Audit Logs                                                          | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.97it/s]

  Ensure Adequate Audit Log Storage                                           | D3FEND=· | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.16it/s]

  Standardize Time Synchronization                                            | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.82it/s]

  Collect Detailed Audit Logs                                                 | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.21it/s]

  Collect DNS Query Audit Logs                                                | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.31it/s]

  Collect URL Request Audit Logs                                              | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 65.34it/s]

  Collect Command-Line Audit Logs                                             | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.31it/s]

  Centralize Audit Logs                                                       | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.76it/s]

  Conduct Audit Log Reviews                                                   | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.57it/s]

  Collect Service Provider Logs                                               | D3FEND=✓ | OntoSecAI=✓ | actions=2
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.8_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.9_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.14it/s]

  Ensure Use of Only Fully Supported Browsers and Email Clients               | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 50.75it/s]

  Use DNS Filtering Services                                                  | D3FEND=✓ | OntoSecAI=· | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.15it/s]

  Maintain Network-Based URL Filters                                          | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.18it/s]

  Enforce Network-Based URL Filters                                           | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.51it/s]

  Restrict Unnecessary or Unauthorized Browser and Email Client Extensions    | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.66it/s]

  Implement DMARC                                                             | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.06it/s]

  Block Unnecessary File Types                                                | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.08it/s]

  Deploy Email Server Anti-Malware Protections                                | D3FEND=✓ | OntoSecAI=· | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.22it/s]

  Maintain Email Server Anti-Malware Protections                              | D3FEND=✓ | OntoSecAI=· | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_CIS\CIS.9_leaf_goals_classified.operationalized_qwen.json

==========================================================================================
AI-RMF — 4 goal-model files
==========================================================================================

Processing: E:\Shahin\iso2goalmodel\goal_models_AIRMF\GOVERN_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.40it/s]

  Establish organizational policies, processes, and procedures for mapping, m | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.20it/s]

  Implement organizational policies, processes, and procedures for mapping, m | D3FEND=✓ | OntoSecAI=· | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.32it/s]

  Maintain organizational policies, processes, and procedures for mapping, me | D3FEND=· | OntoSecAI=· | actions=0
      warning: LLM error: Could not parse JSON object from model output: ''

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.27it/s]

  Define roles and responsibilities for AI risk management                    | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.14it/s]

  Document roles and responsibilities for AI risk management                  | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.85it/s]

  Understand roles and responsibilities for AI risk management                | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.13it/s]

  Integrate AI risk management into organizational culture and decision makin | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.47it/s]

  Establish processes to monitor compliance with laws, regulations, and ethic | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.35it/s]

  Allocate resources for AI risk management activities                        | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.27it/s]

  Define processes for internal and external communication about AI risks     | D3FEND=· | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 66.89it/s]

  Implement processes for internal and external communication about AI risks  | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 63.14it/s]

  Establish mechanisms for accountability and transparency related to AI syst | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_AIRMF\GOVERN_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_AIRMF\MANAGE_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.43it/s]

  Establish processes for prioritizing and responding to AI risks             | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.89it/s]

  Align processes for prioritizing and responding to AI risks with organizati | D3FEND=✓ | OntoSecAI=· | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.07it/s]

  Develop AI risk treatment plans                                             | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.96it/s]

  Implement AI risk treatment plans                                           | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.91it/s]

  Maintain AI risk treatment plans                                            | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.89it/s]

  Establish plans for monitoring AI risks and for incident response and recov | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.35it/s]

  Establish processes for communicating AI risk information and decisions     | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.93it/s]

  Exceed processes for updating, remediating, or removing AI systems when ris | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.95it/s]

  Establish processes for continual improvement of AI risk management         | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 50.33it/s]

  Ensure risk treatment decisions are based on prioritized risks, impact anal | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.25it/s]

  Select controls and mitigation actions                                      | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.80it/s]

  Implement controls and mitigation actions to address identified risks       | D3FEND=· | OntoSecAI=· | actions=0
      warning: LLM error: Could not parse JSON object from model output: ''

Batches: 100%|██████████| 1/1 [00:00<00:00, 65.14it/s]

  Document residual risks                                                     | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 65.13it/s]

  Communicate residual risks                                                  | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.70it/s]

  Accept residual risks                                                       | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.55it/s]

  Implement mechanisms for tracking the effectiveness of controls and for rea | D3FEND=✓ | OntoSecAI=· | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 66.94it/s]

  Exercise incident response and recovery processes                           | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.34it/s]

  Improve incident response and recovery processes using lessons learned      | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_AIRMF\MANAGE_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_AIRMF\MAP_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.10it/s]

  Understand intended purposes, beneficial uses, context-specific laws, norms | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.43it/s]

  Document intended purposes, beneficial uses, context-specific laws, norms,  | D3FEND=✓ | OntoSecAI=· | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.42it/s]

  Ensure interdisciplinary AI actors, competencies, and participation reflect | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.93it/s]

  Understand the organization mission and relevant goals for AI technology    | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.73it/s]

  Document the organization mission and relevant goals for AI technology      | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.81it/s]

  Define the business value or context of business use                        | D3FEND=✓ | OntoSecAI=· | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.40it/s]

  Re-evaluate the business value or context of business use                   | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.50it/s]

  Determine organizational risk tolerances                                    | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.14it/s]

  Document organizational risk tolerances                                     | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.19it/s]

  Elicit system requirements and socio-technical implications are considered  | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 49.71it/s]

  Define the specific tasks and methods used to implement the tasks the AI sy | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.14it/s]

  Document information about knowledge limits and human oversight of the AI s | D3FEND=· | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.61it/s]

  Identify scientific integrity and TEVV considerations                       | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.55it/s]

  Document scientific integrity and TEVV considerations                       | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.38it/s]

  Examine potential benefits of intended AI system functionality and performa | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.87it/s]

  Document potential benefits of intended AI system functionality and perform | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.38it/s]

  Examine potential costs from expected or realized AI errors or functionalit | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.17it/s]

  Document potential costs from expected or realized AI errors or functionali | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 67.64it/s]

  Specify targeted application scope                                          | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.96it/s]

  Document targeted application scope based on system capability and context  | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.02it/s]

  Define processes for operator and practitioner proficiency                  | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.06it/s]

  Assess processes for operator and practitioner proficiency                  | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.65it/s]

  Document processes for operator and practitioner proficiency                | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 49.57it/s]

  Define processes for human oversight                                        | D3FEND=· | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.14it/s]

  Assess processes for human oversight                                        | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.95it/s]

  Document processes for human oversight                                      | D3FEND=· | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.97it/s]

  Document approaches for mapping AI technology and legal risks of components | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.90it/s]

  Identify internal risk controls for components of the AI system, including  | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.55it/s]

  Document internal risk controls for components of the AI system, including  | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.57it/s]

  Document likelihood and magnitude of each identified impact                 | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 50.34it/s]

  Ensure practices and personnel for supporting regular engagement with relev | D3FEND=· | OntoSecAI=✓ | actions=3
Saved: E:\Shahin\iso2goalmodel\goal_models_AIRMF\MAP_leaf_goals_classified.operationalized_qwen.json

Processing: E:\Shahin\iso2goalmodel\goal_models_AIRMF\MEASURE_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.59it/s]

  Select approaches and metrics for measurement of AI risks for implementatio | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.38it/s]

  Assess appropriateness of AI metrics and effectiveness of existing controls | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.86it/s]

  Update appropriateness of AI metrics and effectiveness of existing controls | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.18it/s]

  Involve independent assessors and relevant stakeholders in regular assessme | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.90it/s]

  Document test sets, metrics, and details about the tools used during TEVV   | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.49it/s]

  Ensure evaluations involving human subjects meet applicable requirements an | D3FEND=· | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.66it/s]

  Measure AI system performance or assurance criteria                         | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.33it/s]

  Document AI system performance or assurance criteria                        | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.05it/s]

  Monitor the functionality and behavior of the AI system and its components  | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.96it/s]

  Demonstrate the AI system to be deployed to be valid and reliable           | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.09it/s]

  Evaluate the AI system regularly for safety risks                           | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.21it/s]

  Demonstrate the AI system to be safe within risk tolerance                  | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 63.38it/s]

  Evaluate AI system security and resilience                                  | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.58it/s]

  Document AI system security and resilience                                  | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.55it/s]

  Examine risks associated with transparency and accountability               | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.00it/s]

  Document risks associated with transparency and accountability              | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.76it/s]

  Explain the AI model                                                        | D3FEND=· | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.89it/s]

  Validate the AI model                                                       | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.61it/s]

  Document the AI model                                                       | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.39it/s]

  Interpret output within context                                             | D3FEND=· | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.71it/s]

  Examine privacy risk of the AI system                                       | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.11it/s]

  Document privacy risk of the AI system                                      | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.26it/s]

  Evaluate fairness and bias and results are documented                       | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.31it/s]

  Assess environmental impact and sustainability                              | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.89it/s]

  Document environmental impact and sustainability                            | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.63it/s]

  Evaluate effectiveness of the TEVV metrics and processes                    | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.65it/s]

  Document effectiveness of the TEVV metrics and processes                    | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 40.85it/s]

  Ensure approaches, personnel, and documentation are in place to regularly i | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.39it/s]

  Consider risk tracking approaches where AI risks are difficult to assess or | D3FEND=· | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.28it/s]

  Establish feedback processes for end users and impacted communities         | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.46it/s]

  Integrate feedback processes for end users and impacted communities into ev | D3FEND=· | OntoSecAI=✓ | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.89it/s]

  Ensure measurement approaches are connected to deployment contexts and info | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.85it/s]

  Inform measurement results to validate intended performance                 | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.26it/s]

  Identify measurable performance improvements or declines                    | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.37it/s]

  Document measurable performance improvements or declines                    | D3FEND=✓ | OntoSecAI=· | actions=2
Saved: E:\Shahin\iso2goalmodel\goal_models_AIRMF\MEASURE_leaf_goals_classified.operationalized_qwen.json

==================================================================================================================================================
SUMMARY — PER JSON
==================================================================================================================================================

[A.10.1_leaf_goals_classified.json]
  Goals                              : 6
  Leaf goals                         : 4
  ORG goals                          : 0
  PHYS goals                         : 0
  TECH goals                         : 4
  ORG operationalized D3FEND         : 0
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 4
  ORG operationalized OntoSecAI      : 0
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 2

[A.11.1_leaf_goals_classified.json]
  Goals                              : 13
  Leaf goals                         : 11
  ORG goals                          : 0
  PHYS goals                         : 11
  TECH goals                         : 0
  ORG operationalized D3FEND         : 0
  PHYS operationalized D3FEND        : 11
  TECH operationalized D3FEND        : 0
  ORG operationalized OntoSecAI      : 0
  PHYS operationalized OntoSecAI     : 4
  TECH operationalized OntoSecAI     : 0

[A.5.1_leaf_goals_classified.json]
  Goals                              : 8
  Leaf goals                         : 6
  ORG goals                          : 6
  PHYS goals                         : 0
  TECH goals                         : 0
  ORG operationalized D3FEND         : 6
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 0
  ORG operationalized OntoSecAI      : 5
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 0

[A.6.1_leaf_goals_classified.json]
  Goals                              : 8
  Leaf goals                         : 6
  ORG goals                          : 6
  PHYS goals                         : 0
  TECH goals                         : 0
  ORG operationalized D3FEND         : 5
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 0
  ORG operationalized OntoSecAI      : 5
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 0

[A.6.2_leaf_goals_classified.json]
  Goals                              : 6
  Leaf goals                         : 4
  ORG goals                          : 0
  PHYS goals                         : 1
  TECH goals                         : 3
  ORG operationalized D3FEND         : 0
  PHYS operationalized D3FEND        : 1
  TECH operationalized D3FEND        : 3
  ORG operationalized OntoSecAI      : 0
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 2

[A.7.1_leaf_goals_classified.json]
  Goals                              : 4
  Leaf goals                         : 2
  ORG goals                          : 2
  PHYS goals                         : 0
  TECH goals                         : 0
  ORG operationalized D3FEND         : 1
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 0
  ORG operationalized OntoSecAI      : 2
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 0

[A.7.2_leaf_goals_classified.json]
  Goals                              : 5
  Leaf goals                         : 3
  ORG goals                          : 3
  PHYS goals                         : 0
  TECH goals                         : 0
  ORG operationalized D3FEND         : 1
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 0
  ORG operationalized OntoSecAI      : 2
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 0

[A.7.3_leaf_goals_classified.json]
  Goals                              : 5
  Leaf goals                         : 3
  ORG goals                          : 3
  PHYS goals                         : 0
  TECH goals                         : 0
  ORG operationalized D3FEND         : 2
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 0
  ORG operationalized OntoSecAI      : 1
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 0

[A.8.1_leaf_goals_classified.json]
  Goals                              : 9
  Leaf goals                         : 7
  ORG goals                          : 7
  PHYS goals                         : 0
  TECH goals                         : 0
  ORG operationalized D3FEND         : 5
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 0
  ORG operationalized OntoSecAI      : 4
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 0

[A.8.2_leaf_goals_classified.json]
  Goals                              : 7
  Leaf goals                         : 5
  ORG goals                          : 5
  PHYS goals                         : 0
  TECH goals                         : 0
  ORG operationalized D3FEND         : 4
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 0
  ORG operationalized OntoSecAI      : 5
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 0

[A.8.3_leaf_goals_classified.json]
  Goals                              : 5
  Leaf goals                         : 3
  ORG goals                          : 1
  PHYS goals                         : 1
  TECH goals                         : 1
  ORG operationalized D3FEND         : 1
  PHYS operationalized D3FEND        : 1
  TECH operationalized D3FEND        : 1
  ORG operationalized OntoSecAI      : 1
  PHYS operationalized OntoSecAI     : 1
  TECH operationalized OntoSecAI     : 0

[A.9.1_leaf_goals_classified.json]
  Goals                              : 6
  Leaf goals                         : 4
  ORG goals                          : 1
  PHYS goals                         : 1
  TECH goals                         : 2
  ORG operationalized D3FEND         : 1
  PHYS operationalized D3FEND        : 1
  TECH operationalized D3FEND        : 2
  ORG operationalized OntoSecAI      : 1
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 2

[A.9.2_leaf_goals_classified.json]
  Goals                              : 10
  Leaf goals                         : 8
  ORG goals                          : 1
  PHYS goals                         : 1
  TECH goals                         : 6
  ORG operationalized D3FEND         : 1
  PHYS operationalized D3FEND        : 1
  TECH operationalized D3FEND        : 6
  ORG operationalized OntoSecAI      : 1
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 5

[A.9.3_leaf_goals_classified.json]
  Goals                              : 3
  Leaf goals                         : 1
  ORG goals                          : 1
  PHYS goals                         : 0
  TECH goals                         : 0
  ORG operationalized D3FEND         : 1
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 0
  ORG operationalized OntoSecAI      : 1
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 0

[A.9.4_leaf_goals_classified.json]
  Goals                              : 7
  Leaf goals                         : 5
  ORG goals                          : 0
  PHYS goals                         : 0
  TECH goals                         : 5
  ORG operationalized D3FEND         : 0
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 5
  ORG operationalized OntoSecAI      : 0
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 4

[A.10_leaf_goals_classified.json]
  Goals                              : 8
  Leaf goals                         : 6
  ORG goals                          : 5
  PHYS goals                         : 0
  TECH goals                         : 1
  ORG operationalized D3FEND         : 4
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 0
  ORG operationalized OntoSecAI      : 4
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 1

[A.2_leaf_goals_classified.json]
  Goals                              : 5
  Leaf goals                         : 3
  ORG goals                          : 3
  PHYS goals                         : 0
  TECH goals                         : 0
  ORG operationalized D3FEND         : 2
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 0
  ORG operationalized OntoSecAI      : 2
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 0

[A.3_leaf_goals_classified.json]
  Goals                              : 8
  Leaf goals                         : 6
  ORG goals                          : 5
  PHYS goals                         : 0
  TECH goals                         : 1
  ORG operationalized D3FEND         : 3
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 1
  ORG operationalized OntoSecAI      : 4
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 1

[A.4_leaf_goals_classified.json]
  Goals                              : 7
  Leaf goals                         : 5
  ORG goals                          : 3
  PHYS goals                         : 0
  TECH goals                         : 2
  ORG operationalized D3FEND         : 0
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 1
  ORG operationalized OntoSecAI      : 2
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 2

[A.5_leaf_goals_classified.json]
  Goals                              : 7
  Leaf goals                         : 5
  ORG goals                          : 4
  PHYS goals                         : 0
  TECH goals                         : 1
  ORG operationalized D3FEND         : 3
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 1
  ORG operationalized OntoSecAI      : 3
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 1

[A.6_leaf_goals_classified.json]
  Goals                              : 10
  Leaf goals                         : 8
  ORG goals                          : 1
  PHYS goals                         : 0
  TECH goals                         : 7
  ORG operationalized D3FEND         : 1
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 6
  ORG operationalized OntoSecAI      : 1
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 7

[A.7_leaf_goals_classified.json]
  Goals                              : 11
  Leaf goals                         : 9
  ORG goals                          : 4
  PHYS goals                         : 0
  TECH goals                         : 5
  ORG operationalized D3FEND         : 3
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 5
  ORG operationalized OntoSecAI      : 3
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 4

[A.8_leaf_goals_classified.json]
  Goals                              : 6
  Leaf goals                         : 4
  ORG goals                          : 3
  PHYS goals                         : 0
  TECH goals                         : 1
  ORG operationalized D3FEND         : 0
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 1
  ORG operationalized OntoSecAI      : 3
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 1

[A.9_leaf_goals_classified.json]
  Goals                              : 7
  Leaf goals                         : 5
  ORG goals                          : 3
  PHYS goals                         : 0
  TECH goals                         : 2
  ORG operationalized D3FEND         : 1
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 2
  ORG operationalized OntoSecAI      : 3
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 2

[AC_leaf_goals_classified.json]
  Goals                              : 14
  Leaf goals                         : 12
  ORG goals                          : 2
  PHYS goals                         : 1
  TECH goals                         : 9
  ORG operationalized D3FEND         : 2
  PHYS operationalized D3FEND        : 1
  TECH operationalized D3FEND        : 6
  ORG operationalized OntoSecAI      : 1
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 6

[AU_leaf_goals_classified.json]
  Goals                              : 9
  Leaf goals                         : 7
  ORG goals                          : 6
  PHYS goals                         : 0
  TECH goals                         : 1
  ORG operationalized D3FEND         : 5
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 1
  ORG operationalized OntoSecAI      : 5
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 1

[CA_leaf_goals_classified.json]
  Goals                              : 9
  Leaf goals                         : 7
  ORG goals                          : 5
  PHYS goals                         : 0
  TECH goals                         : 2
  ORG operationalized D3FEND         : 4
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 2
  ORG operationalized OntoSecAI      : 3
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 2

[CM_leaf_goals_classified.json]
  Goals                              : 12
  Leaf goals                         : 10
  ORG goals                          : 4
  PHYS goals                         : 0
  TECH goals                         : 6
  ORG operationalized D3FEND         : 3
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 6
  ORG operationalized OntoSecAI      : 3
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 2

[CP_leaf_goals_classified.json]
  Goals                              : 11
  Leaf goals                         : 9
  ORG goals                          : 6
  PHYS goals                         : 0
  TECH goals                         : 3
  ORG operationalized D3FEND         : 3
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 1
  ORG operationalized OntoSecAI      : 4
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 3

[IA_leaf_goals_classified.json]
  Goals                              : 11
  Leaf goals                         : 9
  ORG goals                          : 1
  PHYS goals                         : 3
  TECH goals                         : 5
  ORG operationalized D3FEND         : 1
  PHYS operationalized D3FEND        : 3
  TECH operationalized D3FEND        : 5
  ORG operationalized OntoSecAI      : 0
  PHYS operationalized OntoSecAI     : 2
  TECH operationalized OntoSecAI     : 2

[IR_leaf_goals_classified.json]
  Goals                              : 8
  Leaf goals                         : 6
  ORG goals                          : 6
  PHYS goals                         : 0
  TECH goals                         : 0
  ORG operationalized D3FEND         : 5
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 0
  ORG operationalized OntoSecAI      : 5
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 0

[MA_leaf_goals_classified.json]
  Goals                              : 9
  Leaf goals                         : 7
  ORG goals                          : 3
  PHYS goals                         : 0
  TECH goals                         : 4
  ORG operationalized D3FEND         : 1
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 3
  ORG operationalized OntoSecAI      : 2
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 3

[MP_leaf_goals_classified.json]
  Goals                              : 7
  Leaf goals                         : 5
  ORG goals                          : 0
  PHYS goals                         : 4
  TECH goals                         : 1
  ORG operationalized D3FEND         : 0
  PHYS operationalized D3FEND        : 3
  TECH operationalized D3FEND        : 1
  ORG operationalized OntoSecAI      : 0
  PHYS operationalized OntoSecAI     : 3
  TECH operationalized OntoSecAI     : 1

[PE_leaf_goals_classified.json]
  Goals                              : 9
  Leaf goals                         : 7
  ORG goals                          : 3
  PHYS goals                         : 4
  TECH goals                         : 0
  ORG operationalized D3FEND         : 3
  PHYS operationalized D3FEND        : 4
  TECH operationalized D3FEND        : 0
  ORG operationalized OntoSecAI      : 3
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 0

[PL_leaf_goals_classified.json]
  Goals                              : 6
  Leaf goals                         : 4
  ORG goals                          : 3
  PHYS goals                         : 0
  TECH goals                         : 1
  ORG operationalized D3FEND         : 3
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 1
  ORG operationalized OntoSecAI      : 2
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 1

[PM_leaf_goals_classified.json]
  Goals                              : 6
  Leaf goals                         : 4
  ORG goals                          : 3
  PHYS goals                         : 1
  TECH goals                         : 0
  ORG operationalized D3FEND         : 2
  PHYS operationalized D3FEND        : 1
  TECH operationalized D3FEND        : 0
  ORG operationalized OntoSecAI      : 2
  PHYS operationalized OntoSecAI     : 1
  TECH operationalized OntoSecAI     : 0

[PS_leaf_goals_classified.json]
  Goals                              : 7
  Leaf goals                         : 5
  ORG goals                          : 3
  PHYS goals                         : 2
  TECH goals                         : 0
  ORG operationalized D3FEND         : 2
  PHYS operationalized D3FEND        : 2
  TECH operationalized D3FEND        : 0
  ORG operationalized OntoSecAI      : 1
  PHYS operationalized OntoSecAI     : 1
  TECH operationalized OntoSecAI     : 0

[PT_leaf_goals_classified.json]
  Goals                              : 6
  Leaf goals                         : 4
  ORG goals                          : 4
  PHYS goals                         : 0
  TECH goals                         : 0
  ORG operationalized D3FEND         : 2
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 0
  ORG operationalized OntoSecAI      : 2
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 0

[RA_leaf_goals_classified.json]
  Goals                              : 7
  Leaf goals                         : 5
  ORG goals                          : 4
  PHYS goals                         : 0
  TECH goals                         : 1
  ORG operationalized D3FEND         : 4
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 1
  ORG operationalized OntoSecAI      : 2
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 1

[SA_leaf_goals_classified.json]
  Goals                              : 10
  Leaf goals                         : 8
  ORG goals                          : 5
  PHYS goals                         : 0
  TECH goals                         : 3
  ORG operationalized D3FEND         : 5
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 2
  ORG operationalized OntoSecAI      : 4
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 3

[SC_leaf_goals_classified.json]

Certain goal models can contain an "LLM error". For example in: CIS.11, CIS.12, CIS.1, CIS.2, AC, CA, CP, GOVERN, and MANAGE (9 errors found).

The script must be rerun for these 9 goal models (separately) to resolve the issue.

Modify the input pattern (`INPUT_PATTERN`) in the code.

In [16]:
%run operationalization_via_qwen.py

Input directories:
  ISO 27001    -> E:\Shahin\iso2goalmodel\goal_models_ISO27001
  ISO 42001    -> E:\Shahin\iso2goalmodel\goal_models_ISO42001
  NIST         -> E:\Shahin\iso2goalmodel\goal_models_NIST
  CIS          -> E:\Shahin\iso2goalmodel\goal_models_CIS
  AI-RMF       -> E:\Shahin\iso2goalmodel\goal_models_AIRMF
Input pattern    : MANAGE_leaf_goals_classified.json
Loading D3FEND...
Loading OntoSecAI...

Knowledge-base index
------------------------------------------------------------
D3FEND defensive techniques : 271
OntoSecAI mitigations        : 81

Checking llama.cpp at http://127.0.0.1:11434/v1...
llama.cpp models: qwen3:8b

Loading embedding model: sentence-transformers/all-mpnet-base-v2

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1211.60it/s]

Encoding D3FEND techniques...

Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]

Encoding OntoSecAI mitigations...

Batches: 100%|██████████| 2/2 [00:02<00:00,  1.25s/it]

ISO 27001: no files matching MANAGE_leaf_goals_classified.json in E:\Shahin\iso2goalmodel\goal_models_ISO27001

ISO 42001: no files matching MANAGE_leaf_goals_classified.json in E:\Shahin\iso2goalmodel\goal_models_ISO42001

NIST: no files matching MANAGE_leaf_goals_classified.json in E:\Shahin\iso2goalmodel\goal_models_NIST

CIS: no files matching MANAGE_leaf_goals_classified.json in E:\Shahin\iso2goalmodel\goal_models_CIS

==========================================================================================
AI-RMF — 1 goal-model files
==========================================================================================

Processing: E:\Shahin\iso2goalmodel\goal_models_AIRMF\MANAGE_leaf_goals_classified.json

Batches: 100%|██████████| 1/1 [00:00<00:00, 70.93it/s]

  Establish processes for prioritizing and responding to AI risks             | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.28it/s]

  Align processes for prioritizing and responding to AI risks with organizati | D3FEND=✓ | OntoSecAI=· | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.89it/s]

  Develop AI risk treatment plans                                             | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 65.05it/s]

  Implement AI risk treatment plans                                           | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 75.43it/s]

  Maintain AI risk treatment plans                                            | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 69.43it/s]

  Establish plans for monitoring AI risks and for incident response and recov | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 60.59it/s]

  Establish processes for communicating AI risk information and decisions     | D3FEND=✓ | OntoSecAI=✓ | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 58.15it/s]

  Exceed processes for updating, remediating, or removing AI systems when ris | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.35it/s]

  Establish processes for continual improvement of AI risk management         | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 46.04it/s]

  Ensure risk treatment decisions are based on prioritized risks, impact anal | D3FEND=✓ | OntoSecAI=· | actions=1

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.50it/s]

  Select controls and mitigation actions                                      | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 59.19it/s]

  Implement controls and mitigation actions to address identified risks       | D3FEND=✓ | OntoSecAI=✓ | actions=5

Batches: 100%|██████████| 1/1 [00:00<00:00, 61.95it/s]

  Document residual risks                                                     | D3FEND=· | OntoSecAI=· | actions=0

Batches: 100%|██████████| 1/1 [00:00<00:00, 64.34it/s]

  Communicate residual risks                                                  | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 67.83it/s]

  Accept residual risks                                                       | D3FEND=✓ | OntoSecAI=· | actions=2

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.16it/s]

  Implement mechanisms for tracking the effectiveness of controls and for rea | D3FEND=✓ | OntoSecAI=✓ | actions=4

Batches: 100%|██████████| 1/1 [00:00<00:00, 55.34it/s]

  Exercise incident response and recovery processes                           | D3FEND=✓ | OntoSecAI=✓ | actions=3

Batches: 100%|██████████| 1/1 [00:00<00:00, 56.41it/s]

  Improve incident response and recovery processes using lessons learned      | D3FEND=✓ | OntoSecAI=✓ | actions=5
Saved: E:\Shahin\iso2goalmodel\goal_models_AIRMF\MANAGE_leaf_goals_classified.operationalized_qwen.json

==================================================================================================================================================
SUMMARY — PER JSON
==================================================================================================================================================

[MANAGE_leaf_goals_classified.json]
  Goals                              : 20
  Leaf goals                         : 18
  ORG goals                          : 15
  PHYS goals                         : 0
  TECH goals                         : 3
  ORG operationalized D3FEND         : 14
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 3
  ORG operationalized OntoSecAI      : 10
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 3

--------------------------------------------------------------------------------------------------------------------------------------------------
[TOTAL]
  Goals                              : 20
  Leaf goals                         : 18
  ORG goals                          : 15
  PHYS goals                         : 0
  TECH goals                         : 3
  ORG operationalized D3FEND         : 14
  PHYS operationalized D3FEND        : 0
  TECH operationalized D3FEND        : 3
  ORG operationalized OntoSecAI      : 10
  PHYS operationalized OntoSecAI     : 0
  TECH operationalized OntoSecAI     : 3

### Operationalization (via keyword search)

In [94]:
%run operationalization_keyword_search.py

loading ontologies ...
  D3FEND    : 142 artifacts, 252 restrictions
  OntoSecAI : 79 mitigations, 33 attacks

=== ISO 27001  (15 models, goal_models_ISO27001/) ===
  Input files: *_leaf_goals_classified.json
  model      leaf | ORG PHYS TECH |  D3F  ONTO  both  none  acts
  A.10.1        4 |   0    0    4 |    0     0     0     4     0
  A.11.1       11 |   0   11    0 |    0     5     0     6     6
  A.5.1         6 |   6    0    0 |    0     0     0     6     0
  A.6.1         6 |   6    0    0 |    0     0     0     6     0
  A.6.2         4 |   0    1    3 |    0     0     0     4     0
  A.7.1         2 |   2    0    0 |    0     0     0     2     0
  A.7.2         3 |   3    0    0 |    0     0     0     3     0
  A.7.3         3 |   3    0    0 |    0     0     0     3     0
  A.8.1         7 |   7    0    0 |    0     0     0     7     0
  A.8.2         5 |   5    0    0 |    0     0     0     5     0
  A.8.3         3 |   1    1    1 |    2     0     0     1     2
  A.9.1         4 |   1    1    2 |    0     4     0     0     6
  A.9.2         8 |   1    1    6 |    7     3     2     0    15
  A.9.3         1 |   1    0    0 |    0     1     0     0     2
  A.9.4         5 |   0    0    5 |    3     3     3     2     8

=== ISO 42001  (9 models, goal_models_ISO42001/) ===
  Input files: *_leaf_goals_classified.json
  model      leaf | ORG PHYS TECH |  D3F  ONTO  both  none  acts
  A.10          6 |   5    0    1 |    0     3     0     3     5
  A.2           3 |   3    0    0 |    0     0     0     3     0
  A.3           6 |   5    0    1 |    0     0     0     6     0
  A.4           5 |   3    0    2 |    0     0     0     5     0
  A.5           5 |   4    0    1 |    0     0     0     5     0
  A.6           8 |   1    0    7 |    0     0     0     8     0
  A.7           9 |   4    0    5 |    0     1     0     8     1
  A.8           4 |   3    0    1 |    0     0     0     4     0
  A.9           5 |   3    0    2 |    0     1     0     4     2

=== NIST  (19 models, goal_models_NIST/) ===
  Input files: *_leaf_goals_classified.json
  model      leaf | ORG PHYS TECH |  D3F  ONTO  both  none  acts
  AC           12 |   2    1    9 |    1     6     0     5     7
  AU            7 |   6    0    1 |    1     0     0     6     3
  CA            7 |   5    0    2 |    0     0     0     7     0
  CM           10 |   4    0    6 |    0     0     0    10     0
  CP            9 |   6    0    3 |    0     0     0     9     0
  IA            9 |   1    3    5 |    0     2     0     7     3
  IR            6 |   6    0    0 |    0     0     0     6     0
  MA            7 |   3    0    4 |    0     0     0     7     0
  MP            5 |   0    4    1 |    2     0     0     3     2
  PE            7 |   3    4    0 |    0     1     0     6     1
  PL            4 |   3    0    1 |    0     0     0     4     0
  PM            4 |   3    1    0 |    0     1     0     3     3
  PS            5 |   3    2    0 |    0     0     0     5     0
  PT            4 |   4    0    0 |    1     1     0     2     6
  RA            5 |   4    0    1 |    0     0     0     5     0
  SA            8 |   5    0    3 |    0     1     0     7     3
  SC            8 |   0    3    5 |    0     1     0     7     3
  SI            8 |   4    0    4 |    0     4     0     4     6
  SR            7 |   7    0    0 |    0     7     0     0    13

=== CIS  (18 models, goal_models_CIS/) ===
  Input files: *_leaf_goals_classified.json
  model      leaf | ORG PHYS TECH |  D3F  ONTO  both  none  acts
  CIS.10        8 |   0    0    8 |    2     0     0     6     2
  CIS.11        7 |   1    0    6 |    0     0     0     7     0
  CIS.12       11 |   1    1    9 |    1     2     0     8     4
  CIS.13       10 |   0    0   10 |    2     4     2     6    10
  CIS.14       10 |  10    0    0 |    0     1     0     9     1
  CIS.15        9 |   6    0    3 |    0     0     0     9     0
  CIS.16       16 |   2    1   13 |    2     7     1     8    17
  CIS.17       13 |  11    1    1 |    0     0     0    13     0
  CIS.18        6 |   1    2    3 |    0     0     0     6     0
  CIS.1         6 |   2    1    3 |    0     0     0     6     0
  CIS.2         8 |   0    2    6 |    1     0     0     7     1
  CIS.3        15 |   2    1   12 |    0     4     0    11     4
  CIS.4        15 |   1    3   11 |    3     0     0    12     3
  CIS.5         8 |   3    1    4 |    3     0     0     5     4
  CIS.6        10 |   0    4    6 |    0     5     0     5     6
  CIS.7         9 |   3    0    6 |    0     0     0     9     0
  CIS.8        11 |   1    0   10 |    0     0     0    11     0
  CIS.9         9 |   0    0    9 |    4     0     0     5     7

=== AI-RMF  (4 models, goal_models_AIRMF/) ===
  Input files: *_leaf_goals_classified.json
  model      leaf | ORG PHYS TECH |  D3F  ONTO  both  none  acts
  GOVERN       12 |  12    0    0 |    0     0     0    12     0
  MANAGE       18 |  15    0    3 |    0     0     0    18     0
  MAP          31 |  29    0    2 |    0     4     0    27     4
  MEASURE      35 |  26    1    8 |    0     5     0    30     9

==========================================================================================
SUMMARY
  Input pattern : *_leaf_goals_classified.json
  Output suffix : .operationalized_keyword_search.json
  Classification is read from the input files; a leaf without a valid class stops the run.

  standard            leaf |  ORG  PHYS  TECH |  D3FEND  OntoSecAI  both  none  acts
  ISO 27001             72 |   36    15    21 |      12         16     5    49    39
  ISO 42001             51 |   31     0    20 |       0          5     0    46     8
  NIST                 132 |   69    18    45 |       5         24     0   103    50
  CIS                  181 |   44    17   120 |      18         23     3   143    59
  AI-RMF                96 |   82     1    13 |       0          9     0    87    13
  TOTAL                532 |  262    51   219 |      35         77     8   428   169

Unmapped goal verbs:
  accept: 1
  acquire: 1
  address: 5
  adopt: 1
  align: 2
  allocate: 4
  approve: 3
  assign: 3
  carry: 1
  centralize: 4
  check: 1
  communicate: 3
  conduct: 8
  consider: 1
  decommission: 1
  define: 18
  demonstrate: 2
  design: 4
  designate: 1
  develop: 31
  display: 1
  dispose: 2
  disseminate: 19
  document: 51
  elicit: 1
  enable: 1
  ensure: 17
  escalate: 1
  establish: 43
  exceed: 1
  exercise: 1
  explain: 1
  generate: 1
  handle: 1
  improve: 1
  include: 1
  inform: 1
  integrate: 2
  interpret: 1
  involve: 1
  make: 1
  only: 1
  operate: 1
  perform: 13
  plan: 1
  process: 1
  provide: 4
  publish: 1
  re-evaluate: 1
  receive: 2
  report: 2
  require: 5
  retain: 2
  return: 1
  screen: 1
  segment: 1
  specify: 1
  standardize: 1
  state: 1
  store: 1
  support: 1
  train: 8
  understand: 3
  uninstall: 1

### Goal models merging into a Graph (Knowledge Base)

Modify the default input pattern in the code: DEFAULT_INPUT_PATTERN="*_leaf_goals_classified.operationalized_embeddings.json" ("embeddings" for goal models generated using embedding techniques). Replace "embeddings" by "llm_qwen" for goal models generated using Qwen. And run the script `json_goal_models_to_graph.py`.

Or, the script can be executed by mentioning the output using `--output`.

In [ ]:
%run json_goal_models_to_graph.py --output ./merged_goal_models_embedding.ttl

In [ ]:
%run json_goal_models_to_graph.py --input-pattern *_leaf_goals_classified.operationalized_keyword_search.json --output ./merged_goal_models_kws.ttl

### Load the Knowledge Base

In [ ]:
from pyoxigraph import Store, RdfFormat

store = Store()

store.load(
    path="../merged_goal_models_embedding.ttl",
    format=RdfFormat.TURTLE,
)

### Tests - Traceability

In [55]:
query = """
PREFIX gm: <https://example.org/goal-model/ontology/>

SELECT
    ?standard
    ?goalId
    ?goalName
    ?operationId
    ?operationName
    ?source
    ?score
WHERE {
    ?goal a gm:LeafGoal ;
          gm:standardName ?standard ;
          gm:goalId ?goalId ;
          gm:goalName ?goalName ;
          gm:operationalizedBy ?operation .

    ?operation gm:operationId ?operationId ;
               gm:operationName ?operationName ;
               gm:source ?source .

    << ?goal gm:operationalizedBy ?operation >>
        gm:similarityScore ?score .
}
ORDER BY ?standard ?goalId DESC(?score)
"""

In [56]:
import pandas as pd

results = store.query(query)

rows = [
    {
        "Standard": row["standard"].value,
        "Goal ID": row["goalId"].value,
        "Leaf Goal": row["goalName"].value,
        "Operation ID": row["operationId"].value,
        "Operation": row["operationName"].value,
        "Source": row["source"].value,
        "Score": float(row["score"].value),
    }
    for row in results
]

df = pd.DataFrame(rows)

df

,Standard,Goal ID,Leaf Goal,Operation ID,Operation,Source,Score
0,AI-RMF,G1.1.1,"Establish organizational policies, processes, ...",AML.M0001,Limit Release of Public Information,OntoSecAI,0.609957
1,AI-RMF,G1.1.1,"Establish organizational policies, processes, ...",AML.M0018,User Training,OntoSecAI,0.577521
2,AI-RMF,G1.1.1,Select approaches and metrics for measurement ...,AML.M0008,Validate ML Model,OntoSecAI,0.577417
3,AI-RMF,G1.1.1,Establish processes for prioritizing and respo...,OWASP.M0009,Use-Case Specific Training,OntoSecAI,0.571408
4,AI-RMF,G1.1.1,Establish processes for prioritizing and respo...,OWASP.M0020,Fine-Tuning Caution,OntoSecAI,0.570934
...,...,...,...,...,...,...,...
1299,NIST,G1.9.1,Prevent further access to the system by initia...,D3-SCF,System Call Filtering,D3FEND,0.552369
1300,NIST,G1.9.1,Prevent further access to the system by initia...,D3-AL,Account Locking,D3FEND,0.539438
1301,NIST,G1.9.1,Prevent further access to the system by initia...,D3-IOPR,IO Port Restriction,D3FEND,0.532736
1302,NIST,G1.9.1,Prevent further access to the system by initia...,D3-EPL,Physical Locking,D3FEND,0.531942
1303,NIST,G1.9.1,Prevent further access to the system by initia...,AML.M0038,Prevent Manipulation,OntoSecAI,0.461028

In [57]:
df[
    (df["Standard"] == "AI-RMF") &
    (df["Goal ID"] == "G1.1.1")
].sort_values("Score", ascending=False)

,Standard,Goal ID,Leaf Goal,Operation ID,Operation,Source,Score
0,AI-RMF,G1.1.1,"Establish organizational policies, processes, ...",AML.M0001,Limit Release of Public Information,OntoSecAI,0.609957
1,AI-RMF,G1.1.1,"Establish organizational policies, processes, ...",AML.M0018,User Training,OntoSecAI,0.577521
2,AI-RMF,G1.1.1,Select approaches and metrics for measurement ...,AML.M0008,Validate ML Model,OntoSecAI,0.577417
3,AI-RMF,G1.1.1,Establish processes for prioritizing and respo...,OWASP.M0009,Use-Case Specific Training,OntoSecAI,0.571408
4,AI-RMF,G1.1.1,Establish processes for prioritizing and respo...,OWASP.M0020,Fine-Tuning Caution,OntoSecAI,0.570934
5,AI-RMF,G1.1.1,Establish processes for prioritizing and respo...,AML.M0001,Limit Release of Public Information,OntoSecAI,0.570058
6,AI-RMF,G1.1.1,Select approaches and metrics for measurement ...,OWASP.M0020,Fine-Tuning Caution,OntoSecAI,0.568593
7,AI-RMF,G1.1.1,Establish processes for prioritizing and respo...,AML.M0018,User Training,OntoSecAI,0.568160
8,AI-RMF,G1.1.1,Select approaches and metrics for measurement ...,AML.M0001,Limit Release of Public Information,OntoSecAI,0.561335
9,AI-RMF,G1.1.1,Select approaches and metrics for measurement ...,AML.M0016,Vulnerability Scanning,OntoSecAI,0.552396
10,AI-RMF,G1.1.1,Establish processes for prioritizing and respo...,OWASP.M0032,Secure Coding,OntoSecAI,0.551993
11,AI-RMF,G1.1.1,Select approaches and metrics for measurement ...,AML.M0018,User Training,OntoSecAI,0.551461
12,AI-RMF,G1.1.1,"Establish organizational policies, processes, ...",OWASP.M0009,Use-Case Specific Training,OntoSecAI,0.550302
13,AI-RMF,G1.1.1,"Establish organizational policies, processes, ...",OWASP.M0032,Secure Coding,OntoSecAI,0.541245
14,AI-RMF,G1.1.1,"Establish organizational policies, processes, ...",AML.M0008,Validate ML Model,OntoSecAI,0.534214
15,AI-RMF,G1.1.1,"Establish organizational policies, processes, ...",D3-SYSVA,System Vulnerability Assessment,D3FEND,0.467399
16,AI-RMF,G1.1.1,Select approaches and metrics for measurement ...,D3-SYSVA,System Vulnerability Assessment,D3FEND,0.453454

#### Operation → Root Goal

In [58]:
query = """
PREFIX gm: <https://example.org/goal-model/ontology/>

SELECT
    ?source
    ?operationId
    ?operationName
    ?score
    ?standard
    ?leafGoalId
    ?leafGoalName
    ?objectiveGoalId
    ?objectiveGoalName
    ?rootGoalId
    ?rootGoalName
WHERE {
    # Operation
    ?operation a gm:Operation ;
               gm:source ?source ;
               gm:operationId ?operationId ;
               gm:operationName ?operationName .

    # Leaf Goal operationalized by the operation
    ?leafGoal a gm:LeafGoal ;
              gm:standardName ?standard ;
              gm:goalId ?leafGoalId ;
              gm:goalName ?leafGoalName ;
              gm:parentGoal ?objectiveGoal ;
              gm:operationalizedBy ?operation .

    # Score attached to the Goal -> Operation relation
    << ?leafGoal gm:operationalizedBy ?operation >>
        gm:similarityScore ?score .

    # Objective Goal
    ?objectiveGoal a gm:ObjectiveGoal ;
                   gm:goalId ?objectiveGoalId ;
                   gm:goalName ?objectiveGoalName ;
                   gm:parentGoal ?rootGoal .

    # Root Goal
    ?rootGoal a gm:RootGoal ;
              gm:goalId ?rootGoalId ;
              gm:goalName ?rootGoalName .
}
ORDER BY ?operationId ?standard ?rootGoalId ?leafGoalId DESC(?score)
"""

In [63]:
results = store.query(query)

rows = [
    {
        "Source": row["source"].value,
        "Operation ID": row["operationId"].value,
        "Operation": row["operationName"].value,
        "Score": float(row["score"].value),
        "Standard": row["standard"].value,
        "Leaf Goal ID": row["leafGoalId"].value,
        "Leaf Goal": row["leafGoalName"].value,
        "Objective Goal ID": row["objectiveGoalId"].value,
        "Objective Goal": row["objectiveGoalName"].value,
        "Root Goal ID": row["rootGoalId"].value,
        "Root Goal": row["rootGoalName"].value,
    }
    for row in results
]

df = pd.DataFrame(rows)

df

,Source,Operation ID,Operation,Score,Standard,Leaf Goal ID,Leaf Goal,Objective Goal ID,Objective Goal,Root Goal ID,Root Goal
0,OntoSecAI,AML.M0001,Limit Release of Public Information,0.609957,AI-RMF,G1.1.1,"Establish organizational policies, processes, ...",G1,Establish and maintain effective AI risk manag...,G0,Govern AI risk management
1,OntoSecAI,AML.M0001,Limit Release of Public Information,0.570058,AI-RMF,G1.1.1,Establish processes for prioritizing and respo...,G1,Treat and monitor AI risks effectively,G0,Manage AI risks
2,OntoSecAI,AML.M0001,Limit Release of Public Information,0.561335,AI-RMF,G1.1.1,Select approaches and metrics for measurement ...,G1,"Measure and evaluate AI risks, performance, an...",G0,Measure AI risks and performance
3,OntoSecAI,AML.M0001,Limit Release of Public Information,0.599989,AI-RMF,G1.1.2,"Implement organizational policies, processes, ...",G1,Establish and maintain effective AI risk manag...,G0,Govern AI risk management
4,OntoSecAI,AML.M0001,Limit Release of Public Information,0.548051,AI-RMF,G1.1.2,Align processes for prioritizing and respondin...,G1,Treat and monitor AI risks effectively,G0,Manage AI risks
...,...,...,...,...,...,...,...,...,...,...,...
1299,OntoSecAI,OWASP.M0035,Secure Deployment of Models,0.455258,CIS Controls,G1.3.1,Securely Manage Network Infrastructure,G1,"Establish, implement, and actively manage netw...",G0,Ensure network infrastructure management
1300,OntoSecAI,OWASP.M0035,Secure Deployment of Models,0.464640,CIS Controls,G1.6.1,Securely Manage Enterprise Assets and Software,G1,Establish and maintain the secure configuratio...,G0,Secure configuration of enterprise assets and ...
1301,OntoSecAI,OWASP.M0035,Secure Deployment of Models,0.486571,CIS Controls,G1.7.1,Deploy a Host-Based Intrusion Prevention Solution,G1,Operate processes and tooling to establish and...,G0,Ensure network monitoring and defense
1302,OntoSecAI,OWASP.M0035,Secure Deployment of Models,0.476710,CIS Controls,G1.8.1,Deploy a Network Intrusion Prevention Solution,G1,Operate processes and tooling to establish and...,G0,Ensure network monitoring and defense
1303,OntoSecAI,OWASP.M0035,Secure Deployment of Models,0.566136,ISO 42001,G1.3.1,Control deployment of AI systems,G1,Design AI systems and Develop AI systems accor...,G0,Ensure AI system design and development